;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;  Bean Brothers (remake) - for ZX Spectrum Next / N-Go
;
;  (c) 2023 David Crespo - https://github.com/dcrespo3d
;                          https://davidprograma.itch.io
;                          https://www.youtube.com/@Davidprograma
;
;  Based on Bean Brothers for ZX Spectrum 48/128K - (c) 2018 Dave Hughes
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;  This program is free software: you can redistribute it and/or modify
;  it under the terms of the GNU General Public License as published by
;  the Free Software Foundation, either version 3 of the License, or
;  (at your option) any later version.  
;
;  This program is distributed in the hope that it will be useful,
;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;  GNU General Public License for more details.
; 
;  You should have received a copy of the GNU General Public License
;  along with this program.  If not, see <https://www.gnu.org/licenses/>. 
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

SECTION PAGE_44_LEVELS

ORG $0000

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; tables
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _tileset_palgroup_44

_tileset_palgroup_44:
    INCBIN "res/tileset_palgroup.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _tileset_colltable_44

_tileset_colltable_44:
    INCBIN "res/tileset_colltable.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; extended levels - autogenerated by tool
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_21
_levmap_21:
    INCBIN "res/levmap_21.bin"

PUBLIC _levdef_21
_levdef_21:
    INCBIN "res/levdef_21.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_22
_levmap_22:
    INCBIN "res/levmap_22.bin"

PUBLIC _levdef_22
_levdef_22:
    INCBIN "res/levdef_22.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_23
_levmap_23:
    INCBIN "res/levmap_23.bin"

PUBLIC _levdef_23
_levdef_23:
    INCBIN "res/levdef_23.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_24
_levmap_24:
    INCBIN "res/levmap_24.bin"

PUBLIC _levdef_24
_levdef_24:
    INCBIN "res/levdef_24.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_25
_levmap_25:
    INCBIN "res/levmap_25.bin"

PUBLIC _levdef_25
_levdef_25:
    INCBIN "res/levdef_25.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_26
_levmap_26:
    INCBIN "res/levmap_26.bin"

PUBLIC _levdef_26
_levdef_26:
    INCBIN "res/levdef_26.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_27
_levmap_27:
    INCBIN "res/levmap_27.bin"

PUBLIC _levdef_27
_levdef_27:
    INCBIN "res/levdef_27.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_28
_levmap_28:
    INCBIN "res/levmap_28.bin"

PUBLIC _levdef_28
_levdef_28:
    INCBIN "res/levdef_28.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_29
_levmap_29:
    INCBIN "res/levmap_29.bin"

PUBLIC _levdef_29
_levdef_29:
    INCBIN "res/levdef_29.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_30
_levmap_30:
    INCBIN "res/levmap_30.bin"

PUBLIC _levdef_30
_levdef_30:
    INCBIN "res/levdef_30.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_31
_levmap_31:
    INCBIN "res/levmap_31.bin"

PUBLIC _levdef_31
_levdef_31:
    INCBIN "res/levdef_31.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_32
_levmap_32:
    INCBIN "res/levmap_32.bin"

PUBLIC _levdef_32
_levdef_32:
    INCBIN "res/levdef_32.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_33
_levmap_33:
    INCBIN "res/levmap_33.bin"

PUBLIC _levdef_33
_levdef_33:
    INCBIN "res/levdef_33.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_34
_levmap_34:
    INCBIN "res/levmap_34.bin"

PUBLIC _levdef_34
_levdef_34:
    INCBIN "res/levdef_34.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_35
_levmap_35:
    INCBIN "res/levmap_35.bin"

PUBLIC _levdef_35
_levdef_35:
    INCBIN "res/levdef_35.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_36
_levmap_36:
    INCBIN "res/levmap_36.bin"

PUBLIC _levdef_36
_levdef_36:
    INCBIN "res/levdef_36.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_37
_levmap_37:
    INCBIN "res/levmap_37.bin"

PUBLIC _levdef_37
_levdef_37:
    INCBIN "res/levdef_37.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_38
_levmap_38:
    INCBIN "res/levmap_38.bin"

PUBLIC _levdef_38
_levdef_38:
    INCBIN "res/levdef_38.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_39
_levmap_39:
    INCBIN "res/levmap_39.bin"

PUBLIC _levdef_39
_levdef_39:
    INCBIN "res/levdef_39.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_40
_levmap_40:
    INCBIN "res/levmap_40.bin"

PUBLIC _levdef_40
_levdef_40:
    INCBIN "res/levdef_40.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

