;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;  Bean Brothers (remake) - for ZX Spectrum Next / N-Go
;
;  (c) 2023 David Crespo - https://github.com/dcrespo3d
;                          https://davidprograma.itch.io
;                          https://www.youtube.com/@Davidprograma
;
;  Based on Bean Brothers for ZX Spectrum 48/128K - (c) 2018 Dave Hughes
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;  This program is free software: you can redistribute it and/or modify
;  it under the terms of the GNU General Public License as published by
;  the Free Software Foundation, either version 3 of the License, or
;  (at your option) any later version.  
;
;  This program is distributed in the hope that it will be useful,
;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;  GNU General Public License for more details.
; 
;  You should have received a copy of the GNU General Public License
;  along with this program.  If not, see <https://www.gnu.org/licenses/>. 
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

SECTION PAGE_34_LEVELS

ORG $0000

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; tables
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _tileset_palgroup

_tileset_palgroup:
    INCBIN "res/tileset_palgroup.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _tileset_colltable

_tileset_colltable:
    INCBIN "res/tileset_colltable.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; original levels - autogenerated by tool
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_01
_levmap_01:
    INCBIN "res/levmap_01.bin"

PUBLIC _levdef_01
_levdef_01:
    INCBIN "res/levdef_01.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_02
_levmap_02:
    INCBIN "res/levmap_02.bin"

PUBLIC _levdef_02
_levdef_02:
    INCBIN "res/levdef_02.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_03
_levmap_03:
    INCBIN "res/levmap_03.bin"

PUBLIC _levdef_03
_levdef_03:
    INCBIN "res/levdef_03.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_04
_levmap_04:
    INCBIN "res/levmap_04.bin"

PUBLIC _levdef_04
_levdef_04:
    INCBIN "res/levdef_04.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_05
_levmap_05:
    INCBIN "res/levmap_05.bin"

PUBLIC _levdef_05
_levdef_05:
    INCBIN "res/levdef_05.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_06
_levmap_06:
    INCBIN "res/levmap_06.bin"

PUBLIC _levdef_06
_levdef_06:
    INCBIN "res/levdef_06.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_07
_levmap_07:
    INCBIN "res/levmap_07.bin"

PUBLIC _levdef_07
_levdef_07:
    INCBIN "res/levdef_07.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_08
_levmap_08:
    INCBIN "res/levmap_08.bin"

PUBLIC _levdef_08
_levdef_08:
    INCBIN "res/levdef_08.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_09
_levmap_09:
    INCBIN "res/levmap_09.bin"

PUBLIC _levdef_09
_levdef_09:
    INCBIN "res/levdef_09.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_10
_levmap_10:
    INCBIN "res/levmap_10.bin"

PUBLIC _levdef_10
_levdef_10:
    INCBIN "res/levdef_10.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_11
_levmap_11:
    INCBIN "res/levmap_11.bin"

PUBLIC _levdef_11
_levdef_11:
    INCBIN "res/levdef_11.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_12
_levmap_12:
    INCBIN "res/levmap_12.bin"

PUBLIC _levdef_12
_levdef_12:
    INCBIN "res/levdef_12.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_13
_levmap_13:
    INCBIN "res/levmap_13.bin"

PUBLIC _levdef_13
_levdef_13:
    INCBIN "res/levdef_13.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_14
_levmap_14:
    INCBIN "res/levmap_14.bin"

PUBLIC _levdef_14
_levdef_14:
    INCBIN "res/levdef_14.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_15
_levmap_15:
    INCBIN "res/levmap_15.bin"

PUBLIC _levdef_15
_levdef_15:
    INCBIN "res/levdef_15.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_16
_levmap_16:
    INCBIN "res/levmap_16.bin"

PUBLIC _levdef_16
_levdef_16:
    INCBIN "res/levdef_16.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_17
_levmap_17:
    INCBIN "res/levmap_17.bin"

PUBLIC _levdef_17
_levdef_17:
    INCBIN "res/levdef_17.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_18
_levmap_18:
    INCBIN "res/levmap_18.bin"

PUBLIC _levdef_18
_levdef_18:
    INCBIN "res/levdef_18.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_19
_levmap_19:
    INCBIN "res/levmap_19.bin"

PUBLIC _levdef_19
_levdef_19:
    INCBIN "res/levdef_19.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

PUBLIC _levmap_20
_levmap_20:
    INCBIN "res/levmap_20.bin"

PUBLIC _levdef_20
_levdef_20:
    INCBIN "res/levdef_20.bin"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

