///////////////////////////////////////////////////////////////////////////////
//
//  Bean Brothers (remake) - for ZX Spectrum Next / N-Go
//
//  (c) 2023 David Crespo - https://github.com/dcrespo3d
//                          https://davidprograma.itch.io
//                          https://www.youtube.com/@Davidprograma
//
//  Based on Bean Brothers for ZX Spectrum 48/128K - (c) 2018 Dave Hughes
//
///////////////////////////////////////////////////////////////////////////////
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.  
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
// 
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>. 
//
///////////////////////////////////////////////////////////////////////////////

// autogenerated by tool
#ifndef _levels_h
#define _levels_h

#include "types.h"
#include "screen_game.h"

extern u8 level_count;

extern u8 levmap_01[];
extern u8 levdef_01[];

extern u8 levmap_02[];
extern u8 levdef_02[];

extern u8 levmap_03[];
extern u8 levdef_03[];

extern u8 levmap_04[];
extern u8 levdef_04[];

extern u8 levmap_05[];
extern u8 levdef_05[];

extern u8 levmap_06[];
extern u8 levdef_06[];

extern u8 levmap_07[];
extern u8 levdef_07[];

extern u8 levmap_08[];
extern u8 levdef_08[];

extern u8 levmap_09[];
extern u8 levdef_09[];

extern u8 levmap_10[];
extern u8 levdef_10[];

extern u8 levmap_11[];
extern u8 levdef_11[];

extern u8 levmap_12[];
extern u8 levdef_12[];

extern u8 levmap_13[];
extern u8 levdef_13[];

extern u8 levmap_14[];
extern u8 levdef_14[];

extern u8 levmap_15[];
extern u8 levdef_15[];

extern u8 levmap_16[];
extern u8 levdef_16[];

extern u8 levmap_17[];
extern u8 levdef_17[];

extern u8 levmap_18[];
extern u8 levdef_18[];

extern u8 levmap_19[];
extern u8 levdef_19[];

extern u8 levmap_20[];
extern u8 levdef_20[];

extern u8 levmap_21[];
extern u8 levdef_21[];

extern u8 levmap_22[];
extern u8 levdef_22[];

extern u8 levmap_23[];
extern u8 levdef_23[];

extern u8 levmap_24[];
extern u8 levdef_24[];

extern u8 levmap_25[];
extern u8 levdef_25[];

extern u8 levmap_26[];
extern u8 levdef_26[];

extern u8 levmap_27[];
extern u8 levdef_27[];

extern u8 levmap_28[];
extern u8 levdef_28[];

extern u8 levmap_29[];
extern u8 levdef_29[];

extern u8 levmap_30[];
extern u8 levdef_30[];

extern u8 levmap_31[];
extern u8 levdef_31[];

extern u8 levmap_32[];
extern u8 levdef_32[];

extern u8 levmap_33[];
extern u8 levdef_33[];

extern u8 levmap_34[];
extern u8 levdef_34[];

extern u8 levmap_35[];
extern u8 levdef_35[];

extern u8 levmap_36[];
extern u8 levdef_36[];

extern u8 levmap_37[];
extern u8 levdef_37[];

extern u8 levmap_38[];
extern u8 levdef_38[];

extern u8 levmap_39[];
extern u8 levdef_39[];

extern u8 levmap_40[];
extern u8 levdef_40[];

extern u8 *levmap_array[];
extern LevelDef *levdef_array[];

#endif
