///////////////////////////////////////////////////////////////////////////////
//
//  Bean Brothers (remake) - for ZX Spectrum Next / N-Go
//
//  (c) 2023 David Crespo - https://github.com/dcrespo3d
//                          https://davidprograma.itch.io
//                          https://www.youtube.com/@Davidprograma
//
//  Based on Bean Brothers for ZX Spectrum 48/128K - (c) 2018 Dave Hughes
//
///////////////////////////////////////////////////////////////////////////////
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.  
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
// 
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>. 
//
///////////////////////////////////////////////////////////////////////////////

// autogenerated by tool
#include "levels.h"

u8 level_count = 40;

u8 *levmap_array[] = {
    levmap_01,
    levmap_02,
    levmap_03,
    levmap_04,
    levmap_05,
    levmap_06,
    levmap_07,
    levmap_08,
    levmap_09,
    levmap_10,
    levmap_11,
    levmap_12,
    levmap_13,
    levmap_14,
    levmap_15,
    levmap_16,
    levmap_17,
    levmap_18,
    levmap_19,
    levmap_20,
    levmap_21,
    levmap_22,
    levmap_23,
    levmap_24,
    levmap_25,
    levmap_26,
    levmap_27,
    levmap_28,
    levmap_29,
    levmap_30,
    levmap_31,
    levmap_32,
    levmap_33,
    levmap_34,
    levmap_35,
    levmap_36,
    levmap_37,
    levmap_38,
    levmap_39,
    levmap_40,
};

LevelDef *levdef_array[] = {
    levdef_01,
    levdef_02,
    levdef_03,
    levdef_04,
    levdef_05,
    levdef_06,
    levdef_07,
    levdef_08,
    levdef_09,
    levdef_10,
    levdef_11,
    levdef_12,
    levdef_13,
    levdef_14,
    levdef_15,
    levdef_16,
    levdef_17,
    levdef_18,
    levdef_19,
    levdef_20,
    levdef_21,
    levdef_22,
    levdef_23,
    levdef_24,
    levdef_25,
    levdef_26,
    levdef_27,
    levdef_28,
    levdef_29,
    levdef_30,
    levdef_31,
    levdef_32,
    levdef_33,
    levdef_34,
    levdef_35,
    levdef_36,
    levdef_37,
    levdef_38,
    levdef_39,
    levdef_40,
};

