;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;  Bean Brothers (remake) - for ZX Spectrum Next / N-Go
;
;  (c) 2023 David Crespo - https://github.com/dcrespo3d
;                          https://davidprograma.itch.io
;                          https://www.youtube.com/@Davidprograma
;
;  Based on Bean Brothers for ZX Spectrum 48/128K - (c) 2018 Dave Hughes
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;  This program is free software: you can redistribute it and/or modify
;  it under the terms of the GNU General Public License as published by
;  the Free Software Foundation, either version 3 of the License, or
;  (at your option) any later version.  
;
;  This program is distributed in the hope that it will be useful,
;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;  GNU General Public License for more details.
; 
;  You should have received a copy of the GNU General Public License
;  along with this program.  If not, see <https://www.gnu.org/licenses/>. 
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

SECTION PAGE_36_MUSIC
defw 0 ; avoid song potentially placed at $0000, it could be mistaken with NULL
PUBLIC _song_leaving
_song_leaving:

; LeavingTown HB, AKG format, v1.0.

; Generated by Arkos Tracker 2.

LeavingTownHB_Start:
LeavingTownHB_StartDisarkGenerateExternalLabel:

LeavingTownHB_DisarkByteRegionStart0:
	defb "AT20"
LeavingTownHB_DisarkPointerRegionStart1:
	defw LeavingTownHB_ArpeggioTable	; The address of the Arpeggio table.
	defw LeavingTownHB_PitchTable	; The address of the Pitch table.
	defw LeavingTownHB_InstrumentTable	; The address of the Instrument table.
	defw LeavingTownHB_EffectBlockTable	; The address of the Effect Block table.
LeavingTownHB_DisarkPointerRegionEnd1:


; The addresses of each Subsong:
LeavingTownHB_DisarkPointerRegionStart2:
	defw LeavingTownHB_Subsong0_Start
LeavingTownHB_DisarkPointerRegionEnd2:

; Declares all the Arpeggios.
LeavingTownHB_ArpeggioTable:
LeavingTownHB_DisarkPointerRegionStart3:
LeavingTownHB_DisarkPointerRegionEnd3:

; Declares all the Pitches.
LeavingTownHB_PitchTable:
LeavingTownHB_DisarkPointerRegionStart4:
LeavingTownHB_DisarkPointerRegionEnd4:

; Declares all the Instruments.
LeavingTownHB_InstrumentTable:
LeavingTownHB_DisarkPointerRegionStart5:
	defw LeavingTownHB_EmptyInstrument
	defw LeavingTownHB_Instrument1
	defw LeavingTownHB_Instrument2
	defw LeavingTownHB_Instrument3
	defw LeavingTownHB_Instrument4
	defw LeavingTownHB_Instrument5
	defw LeavingTownHB_Instrument6
	defw LeavingTownHB_Instrument7
	defw LeavingTownHB_Instrument8
	defw LeavingTownHB_Instrument9
	defw LeavingTownHB_Instrument10
	defw LeavingTownHB_Instrument11
LeavingTownHB_DisarkPointerRegionEnd5:

LeavingTownHB_EmptyInstrument:
	defb 0	; The speed (>0, 0 for 256).
LeavingTownHB_EmptyInstrument_Loop:	defb 0	; No Soft no Hard. Volume: 0. Noise? false.

	defb 6	; Loop to silence.

LeavingTownHB_Instrument1:
	defb 1	; The speed (>0, 0 for 256).
	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 6	; Loop to silence.

LeavingTownHB_Instrument2:
	defb 1	; The speed (>0, 0 for 256).
	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 6	; Loop to silence.

LeavingTownHB_Instrument3:
	defb 1	; The speed (>0, 0 for 256).
	defb 121	; Soft only. Volume: 15.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb -5	; Arpeggio.

	defb 241	; Soft only. Volume: 14. Volume only.

	defb 105	; Soft only. Volume: 13.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 97	; Soft only. Volume: 12.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb -5	; Arpeggio.

	defb 217	; Soft only. Volume: 11. Volume only.

	defb 81	; Soft only. Volume: 10.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 73	; Soft only. Volume: 9.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb -5	; Arpeggio.

	defb 193	; Soft only. Volume: 8. Volume only.

	defb 65	; Soft only. Volume: 8.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 65	; Soft only. Volume: 8.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb -5	; Arpeggio.

	defb 193	; Soft only. Volume: 8. Volume only.

	defb 6	; Loop to silence.

LeavingTownHB_Instrument4:
	defb 1	; The speed (>0, 0 for 256).
	defb 249	; Soft only. Volume: 15. Volume only.

	defb 113	; Soft only. Volume: 14.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 105	; Soft only. Volume: 13.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

	defb 225	; Soft only. Volume: 12. Volume only.

	defb 89	; Soft only. Volume: 11.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 81	; Soft only. Volume: 10.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

	defb 201	; Soft only. Volume: 9. Volume only.

	defb 65	; Soft only. Volume: 8.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 65	; Soft only. Volume: 8.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

	defb 193	; Soft only. Volume: 8. Volume only.

	defb 65	; Soft only. Volume: 8.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 6	; Loop to silence.

LeavingTownHB_Instrument5:
	defb 1	; The speed (>0, 0 for 256).
	defb 121	; Soft only. Volume: 15.
	defb 70	; Additional data. Noise: 6. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

	defb 121	; Soft only. Volume: 15.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 10	; Arpeggio.

	defb 105	; Soft only. Volume: 13.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 9	; Arpeggio.

	defb 105	; Soft only. Volume: 13.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 8	; Arpeggio.

	defb 89	; Soft only. Volume: 11.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 5	; Arpeggio.

	defb 89	; Soft only. Volume: 11.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 73	; Soft only. Volume: 9.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 57	; Soft only. Volume: 7.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 2	; Arpeggio.

	defb 57	; Soft only. Volume: 7.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 1	; Arpeggio.

	defb 49	; Soft only. Volume: 6.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 1	; Arpeggio.

	defb 177	; Soft only. Volume: 6. Volume only.

	defb 6	; Loop to silence.

LeavingTownHB_Instrument6:
	defb 1	; The speed (>0, 0 for 256).
	defb 121	; Soft only. Volume: 15.
	defb 75	; Additional data. Noise: 11. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

	defb 113	; Soft only. Volume: 14.
	defb 74	; Additional data. Noise: 10. Pitch? false. Arp? true. Period? false.
	defb 13	; Arpeggio.

	defb 105	; Soft only. Volume: 13.
	defb 73	; Additional data. Noise: 9. Pitch? false. Arp? true. Period? false.
	defb 16	; Arpeggio.

	defb 105	; Soft only. Volume: 13.
	defb 72	; Additional data. Noise: 8. Pitch? false. Arp? true. Period? false.
	defb 9	; Arpeggio.

	defb 97	; Soft only. Volume: 12.
	defb 7	; Additional data. Noise: 7. Pitch? false. Arp? false. Period? false.

	defb 81	; Soft only. Volume: 10.
	defb 70	; Additional data. Noise: 6. Pitch? false. Arp? true. Period? false.
	defb 9	; Arpeggio.

	defb 65	; Soft only. Volume: 8.
	defb 69	; Additional data. Noise: 5. Pitch? false. Arp? true. Period? false.
	defb 14	; Arpeggio.

	defb 49	; Soft only. Volume: 6.
	defb 4	; Additional data. Noise: 4. Pitch? false. Arp? false. Period? false.

	defb 33	; Soft only. Volume: 4.
	defb 3	; Additional data. Noise: 3. Pitch? false. Arp? false. Period? false.

	defb 25	; Soft only. Volume: 3.
	defb 2	; Additional data. Noise: 2. Pitch? false. Arp? false. Period? false.

	defb 6	; Loop to silence.

LeavingTownHB_Instrument7:
	defb 1	; The speed (>0, 0 for 256).
	defb 224	; No Soft no Hard. Volume: 12. Noise? true.
	defb 1	; Noise: 1.

	defb 216	; No Soft no Hard. Volume: 11. Noise? true.
	defb 1	; Noise: 1.

	defb 208	; No Soft no Hard. Volume: 10. Noise? true.
	defb 1	; Noise: 1.

	defb 200	; No Soft no Hard. Volume: 9. Noise? true.
	defb 1	; Noise: 1.

	defb 184	; No Soft no Hard. Volume: 7. Noise? true.
	defb 1	; Noise: 1.

	defb 168	; No Soft no Hard. Volume: 5. Noise? true.
	defb 1	; Noise: 1.

	defb 152	; No Soft no Hard. Volume: 3. Noise? true.
	defb 1	; Noise: 1.

	defb 136	; No Soft no Hard. Volume: 1. Noise? true.
	defb 1	; Noise: 1.

	defb 6	; Loop to silence.

LeavingTownHB_Instrument8:
	defb 1	; The speed (>0, 0 for 256).
	defb 249	; Soft only. Volume: 15. Volume only.

	defb 113	; Soft only. Volume: 14.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 105	; Soft only. Volume: 13.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 10	; Arpeggio.

	defb 225	; Soft only. Volume: 12. Volume only.

	defb 89	; Soft only. Volume: 11.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 81	; Soft only. Volume: 10.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 10	; Arpeggio.

	defb 201	; Soft only. Volume: 9. Volume only.

	defb 65	; Soft only. Volume: 8.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 57	; Soft only. Volume: 7.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 10	; Arpeggio.

	defb 177	; Soft only. Volume: 6. Volume only.

	defb 41	; Soft only. Volume: 5.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 33	; Soft only. Volume: 4.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 10	; Arpeggio.

	defb 153	; Soft only. Volume: 3. Volume only.

	defb 17	; Soft only. Volume: 2.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 9	; Soft only. Volume: 1.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 10	; Arpeggio.

	defb 6	; Loop to silence.

LeavingTownHB_Instrument9:
	defb 1	; The speed (>0, 0 for 256).
	defb 249	; Soft only. Volume: 15. Volume only.

	defb 113	; Soft only. Volume: 14.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 105	; Soft only. Volume: 13.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 9	; Arpeggio.

	defb 225	; Soft only. Volume: 12. Volume only.

	defb 89	; Soft only. Volume: 11.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 81	; Soft only. Volume: 10.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 9	; Arpeggio.

	defb 201	; Soft only. Volume: 9. Volume only.

	defb 65	; Soft only. Volume: 8.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 57	; Soft only. Volume: 7.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 9	; Arpeggio.

	defb 177	; Soft only. Volume: 6. Volume only.

	defb 41	; Soft only. Volume: 5.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 33	; Soft only. Volume: 4.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 9	; Arpeggio.

	defb 153	; Soft only. Volume: 3. Volume only.

	defb 17	; Soft only. Volume: 2.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 9	; Soft only. Volume: 1.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 9	; Arpeggio.

	defb 6	; Loop to silence.

LeavingTownHB_Instrument10:
	defb 1	; The speed (>0, 0 for 256).
	defb 249	; Soft only. Volume: 15. Volume only.

	defb 113	; Soft only. Volume: 14.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 105	; Soft only. Volume: 13.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 7	; Arpeggio.

	defb 225	; Soft only. Volume: 12. Volume only.

	defb 89	; Soft only. Volume: 11.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 81	; Soft only. Volume: 10.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 7	; Arpeggio.

	defb 201	; Soft only. Volume: 9. Volume only.

	defb 65	; Soft only. Volume: 8.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 57	; Soft only. Volume: 7.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 7	; Arpeggio.

	defb 177	; Soft only. Volume: 6. Volume only.

	defb 41	; Soft only. Volume: 5.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 33	; Soft only. Volume: 4.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 7	; Arpeggio.

	defb 153	; Soft only. Volume: 3. Volume only.

	defb 17	; Soft only. Volume: 2.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 9	; Soft only. Volume: 1.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 7	; Arpeggio.

	defb 6	; Loop to silence.

LeavingTownHB_Instrument11:
	defb 1	; The speed (>0, 0 for 256).
	defb 249	; Soft only. Volume: 15. Volume only.

	defb 113	; Soft only. Volume: 14.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 105	; Soft only. Volume: 13.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 7	; Arpeggio.

	defb 225	; Soft only. Volume: 12. Volume only.

	defb 89	; Soft only. Volume: 11.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 81	; Soft only. Volume: 10.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 7	; Arpeggio.

	defb 201	; Soft only. Volume: 9. Volume only.

	defb 65	; Soft only. Volume: 8.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 57	; Soft only. Volume: 7.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 7	; Arpeggio.

	defb 177	; Soft only. Volume: 6. Volume only.

	defb 41	; Soft only. Volume: 5.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 33	; Soft only. Volume: 4.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 7	; Arpeggio.

	defb 153	; Soft only. Volume: 3. Volume only.

	defb 17	; Soft only. Volume: 2.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 9	; Soft only. Volume: 1.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 7	; Arpeggio.

	defb 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
LeavingTownHB_EffectBlockTable:

LeavingTownHB_DisarkByteRegionEnd0:

; Subsong 0
; ----------------------
LeavingTownHB_Subsong0_DisarkByteRegionStart0:
LeavingTownHB_Subsong0_Start:
	defb 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	defb 1	; Digichannel (0-2).
	defb 1	; PSG count (>0).
	defb 2	; Loop start index (>=0).
	defb 13	; End index (>=0).
	defb 6	; Initial speed (>=0).
	defb 17	; Base note index (>=0).

LeavingTownHB_Subsong0_Linker:
LeavingTownHB_Subsong0_DisarkPointerRegionStart1:
; Position 0
	defw LeavingTownHB_Subsong0_Track3
	defw LeavingTownHB_Subsong0_Track3
	defw LeavingTownHB_Subsong0_Track0
	defw LeavingTownHB_Subsong0_LinkerBlock0

; Position 1
	defw LeavingTownHB_Subsong0_Track1
	defw LeavingTownHB_Subsong0_Track3
	defw LeavingTownHB_Subsong0_Track2
	defw LeavingTownHB_Subsong0_LinkerBlock1

; Position 2
LeavingTownHB_Subsong0_Linker_Loop:
	defw LeavingTownHB_Subsong0_Track4
	defw LeavingTownHB_Subsong0_Track5
	defw LeavingTownHB_Subsong0_Track2
	defw LeavingTownHB_Subsong0_LinkerBlock1

; Position 3
	defw LeavingTownHB_Subsong0_Track4
	defw LeavingTownHB_Subsong0_Track7
	defw LeavingTownHB_Subsong0_Track6
	defw LeavingTownHB_Subsong0_LinkerBlock1

; Position 4
	defw LeavingTownHB_Subsong0_Track4
	defw LeavingTownHB_Subsong0_Track9
	defw LeavingTownHB_Subsong0_Track8
	defw LeavingTownHB_Subsong0_LinkerBlock1

; Position 5
	defw LeavingTownHB_Subsong0_Track4
	defw LeavingTownHB_Subsong0_Track10
	defw LeavingTownHB_Subsong0_Track8
	defw LeavingTownHB_Subsong0_LinkerBlock2

; Position 6
	defw LeavingTownHB_Subsong0_Track4
	defw LeavingTownHB_Subsong0_Track12
	defw LeavingTownHB_Subsong0_Track11
	defw LeavingTownHB_Subsong0_LinkerBlock1

; Position 7
	defw LeavingTownHB_Subsong0_Track4
	defw LeavingTownHB_Subsong0_Track14
	defw LeavingTownHB_Subsong0_Track13
	defw LeavingTownHB_Subsong0_LinkerBlock1

; Position 8
	defw LeavingTownHB_Subsong0_Track4
	defw LeavingTownHB_Subsong0_Track9
	defw LeavingTownHB_Subsong0_Track8
	defw LeavingTownHB_Subsong0_LinkerBlock1

; Position 9
	defw LeavingTownHB_Subsong0_Track4
	defw LeavingTownHB_Subsong0_Track10
	defw LeavingTownHB_Subsong0_Track8
	defw LeavingTownHB_Subsong0_LinkerBlock2

; Position 10
	defw LeavingTownHB_Subsong0_Track4
	defw LeavingTownHB_Subsong0_Track12
	defw LeavingTownHB_Subsong0_Track11
	defw LeavingTownHB_Subsong0_LinkerBlock1

; Position 11
	defw LeavingTownHB_Subsong0_Track4
	defw LeavingTownHB_Subsong0_Track14
	defw LeavingTownHB_Subsong0_Track13
	defw LeavingTownHB_Subsong0_LinkerBlock1

; Position 12
	defw LeavingTownHB_Subsong0_Track4
	defw LeavingTownHB_Subsong0_Track15
	defw LeavingTownHB_Subsong0_Track16
	defw LeavingTownHB_Subsong0_LinkerBlock1

; Position 13
	defw LeavingTownHB_Subsong0_Track4
	defw LeavingTownHB_Subsong0_Track17
	defw LeavingTownHB_Subsong0_Track18
	defw LeavingTownHB_Subsong0_LinkerBlock1

LeavingTownHB_Subsong0_DisarkPointerRegionEnd1:
	defw 0	; Loop.
LeavingTownHB_Subsong0_DisarkWordForceReference2:
	defw LeavingTownHB_Subsong0_Linker_Loop

LeavingTownHB_Subsong0_LinkerBlock0:
	defb 4	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
LeavingTownHB_Subsong0_DisarkWordForceReference3:
	defw LeavingTownHB_Subsong0_SpeedTrack0	; SpeedTrack address.
LeavingTownHB_Subsong0_DisarkWordForceReference4:
	defw LeavingTownHB_Subsong0_EventTrack0	; EventTrack address.
LeavingTownHB_Subsong0_LinkerBlock1:
	defb 64	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
LeavingTownHB_Subsong0_DisarkWordForceReference5:
	defw LeavingTownHB_Subsong0_SpeedTrack0	; SpeedTrack address.
LeavingTownHB_Subsong0_DisarkWordForceReference6:
	defw LeavingTownHB_Subsong0_EventTrack0	; EventTrack address.
LeavingTownHB_Subsong0_LinkerBlock2:
	defb 32	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
LeavingTownHB_Subsong0_DisarkWordForceReference7:
	defw LeavingTownHB_Subsong0_SpeedTrack0	; SpeedTrack address.
LeavingTownHB_Subsong0_DisarkWordForceReference8:
	defw LeavingTownHB_Subsong0_EventTrack0	; EventTrack address.

LeavingTownHB_Subsong0_Track0:
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 173
	defb 3	; New Instrument (3).
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track1:
	defb 135
	defb 5	; New Instrument (5).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 147
	defb 6	; New Instrument (6).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 135
	defb 5	; New Instrument (5).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 147
	defb 6	; New Instrument (6).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 135
	defb 5	; New Instrument (5).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 147
	defb 6	; New Instrument (6).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 135
	defb 5	; New Instrument (5).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 147
	defb 6	; New Instrument (6).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 135
	defb 5	; New Instrument (5).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 147
	defb 6	; New Instrument (6).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 135
	defb 5	; New Instrument (5).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 147
	defb 6	; New Instrument (6).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 135
	defb 5	; New Instrument (5).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 147
	defb 6	; New Instrument (6).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 135
	defb 5	; New Instrument (5).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 147
	defb 6	; New Instrument (6).
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track2:
	defb 173
	defb 3	; New Instrument (3).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 43
	defb 60	; Waits for 1 line.

	defb 43
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 166
	defb 4	; New Instrument (4).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 38
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 173
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 45
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 45
	defb 60	; Waits for 1 line.

	defb 45
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 43
	defb 60	; Waits for 1 line.

	defb 43
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 43
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 43
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 45
	defb 60	; Waits for 1 line.

	defb 45
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 45
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track3:
	defb 61, 55	; Waits for 56 lines.

	defb 142
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 16
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 21
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track4:
	defb 135
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 147
	defb 6	; New Instrument (6).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 135
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 147
	defb 6	; New Instrument (6).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 135
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 147
	defb 6	; New Instrument (6).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 135
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 147
	defb 6	; New Instrument (6).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 135
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 147
	defb 6	; New Instrument (6).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 135
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 147
	defb 6	; New Instrument (6).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 135
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 147
	defb 6	; New Instrument (6).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 135
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 60	; Waits for 1 line.

	defb 147
	defb 6	; New Instrument (6).
	defb 60	; Waits for 1 line.

	defb 183
	defb 7	; New Instrument (7).
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track5:
	defb 137
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 16
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 21
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 149
	defb 1	; New Instrument (1).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 147
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 16
	defb 60	; Waits for 1 line.

	defb 21
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 16
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 16
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track6:
	defb 173
	defb 3	; New Instrument (3).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 43
	defb 60	; Waits for 1 line.

	defb 43
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 166
	defb 4	; New Instrument (4).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 38
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 173
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 45
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 45
	defb 60	; Waits for 1 line.

	defb 45
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 43
	defb 60	; Waits for 1 line.

	defb 43
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 166
	defb 4	; New Instrument (4).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 38
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 173
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 45
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track7:
	defb 137
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 16
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 21
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 149
	defb 1	; New Instrument (1).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 147
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 16
	defb 60	; Waits for 1 line.

	defb 149
	defb 1	; New Instrument (1).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 147
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 144
	defb 1	; New Instrument (1).
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track8:
	defb 163
	defb 8	; New Instrument (8).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 35
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 35
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 168
	defb 3	; New Instrument (3).
	defb 61, 6	; Waits for 7 lines.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 60	; Waits for 1 line.

	defb 163
	defb 8	; New Instrument (8).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 35
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 35
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 168
	defb 3	; New Instrument (3).
	defb 61, 6	; Waits for 7 lines.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track9:
	defb 139
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 139
	defb 1	; New Instrument (1).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 142
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 11
	defb 60	; Waits for 1 line.

	defb 144
	defb 1	; New Instrument (1).
	defb 61, 6	; Waits for 7 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 146
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 16
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 11
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 139
	defb 1	; New Instrument (1).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 142
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 11
	defb 60	; Waits for 1 line.

	defb 132
	defb 1	; New Instrument (1).
	defb 61, 6	; Waits for 7 lines.

	defb 8
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 136
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 10
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track10:
	defb 139
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 139
	defb 1	; New Instrument (1).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 142
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 11
	defb 60	; Waits for 1 line.

	defb 144
	defb 1	; New Instrument (1).
	defb 61, 6	; Waits for 7 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 136
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 8
	defb 60	; Waits for 1 line.

	defb 9
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track11:
	defb 173
	defb 3	; New Instrument (3).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 45
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 45
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 166
	defb 4	; New Instrument (4).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 38
	defb 61, 6	; Waits for 7 lines.

	defb 38
	defb 60	; Waits for 1 line.

	defb 38
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 173
	defb 3	; New Instrument (3).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 45
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 45
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 166
	defb 4	; New Instrument (4).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 38
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 38
	defb 60	; Waits for 1 line.

	defb 38
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track12:
	defb 137
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 14
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track13:
	defb 171
	defb 3	; New Instrument (3).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 43
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 43
	defb 60	; Waits for 1 line.

	defb 43
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 41
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 41
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 41
	defb 60	; Waits for 1 line.

	defb 41
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 166
	defb 4	; New Instrument (4).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 38
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 38
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 38
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 38
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 38
	defb 60	; Waits for 1 line.

	defb 38
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track14:
	defb 135
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 7
	defb 60	; Waits for 1 line.

	defb 7
	defb 60	; Waits for 1 line.

	defb 7
	defb 60	; Waits for 1 line.

	defb 7
	defb 60	; Waits for 1 line.

	defb 7
	defb 60	; Waits for 1 line.

	defb 7
	defb 60	; Waits for 1 line.

	defb 7
	defb 60	; Waits for 1 line.

	defb 5
	defb 60	; Waits for 1 line.

	defb 5
	defb 60	; Waits for 1 line.

	defb 5
	defb 60	; Waits for 1 line.

	defb 5
	defb 60	; Waits for 1 line.

	defb 5
	defb 60	; Waits for 1 line.

	defb 5
	defb 60	; Waits for 1 line.

	defb 5
	defb 60	; Waits for 1 line.

	defb 5
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 2
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track15:
	defb 139
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 139
	defb 1	; New Instrument (1).
	defb 61, 8	; Waits for 9 lines.

	defb 137
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 11
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 11
	defb 60	; Waits for 1 line.

	defb 142
	defb 1	; New Instrument (1).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 11
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 132
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 132
	defb 1	; New Instrument (1).
	defb 61, 8	; Waits for 9 lines.

	defb 130
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 4
	defb 60	; Waits for 1 line.

	defb 2
	defb 60	; Waits for 1 line.

	defb 4
	defb 60	; Waits for 1 line.

	defb 136
	defb 1	; New Instrument (1).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 137
	defb 2	; New Instrument (2).
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track16:
	defb 163
	defb 8	; New Instrument (8).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 35
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 163
	defb 9	; New Instrument (9).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 35
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 163
	defb 10	; New Instrument (10).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 35
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 163
	defb 8	; New Instrument (8).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 35
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 168
	defb 3	; New Instrument (3).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track17:
	defb 139
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 139
	defb 1	; New Instrument (1).
	defb 61, 8	; Waits for 9 lines.

	defb 137
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 11
	defb 60	; Waits for 1 line.

	defb 9
	defb 60	; Waits for 1 line.

	defb 11
	defb 60	; Waits for 1 line.

	defb 142
	defb 1	; New Instrument (1).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 11
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 144
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 144
	defb 1	; New Instrument (1).
	defb 61, 8	; Waits for 9 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 142
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 11
	defb 60	; Waits for 1 line.

	defb 144
	defb 1	; New Instrument (1).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 142
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 139
	defb 1	; New Instrument (1).
	defb 61, 127	; Waits for 128 lines.


LeavingTownHB_Subsong0_Track18:
	defb 163
	defb 8	; New Instrument (8).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 35
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 163
	defb 9	; New Instrument (9).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 35
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 163
	defb 10	; New Instrument (10).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 35
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 163
	defb 8	; New Instrument (8).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 35
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 173
	defb 3	; New Instrument (3).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 45
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 45
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 45
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 168
	defb 11	; New Instrument (11).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 60	; Waits for 1 line.

	defb 173
	defb 3	; New Instrument (3).
	defb 61, 127	; Waits for 128 lines.


; The speed tracks
LeavingTownHB_Subsong0_SpeedTrack0:
	defb 10	; Value: 5.
	defb 253	; Wait for 127 lines.

; The event tracks
LeavingTownHB_Subsong0_EventTrack0:
	defb 255	; Wait for 128 lines.

LeavingTownHB_Subsong0_DisarkByteRegionEnd0:
