;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;  Bean Brothers (remake) - for ZX Spectrum Next / N-Go
;
;  (c) 2023 David Crespo - https://github.com/dcrespo3d
;                          https://davidprograma.itch.io
;                          https://www.youtube.com/@Davidprograma
;
;  Based on Bean Brothers for ZX Spectrum 48/128K - (c) 2018 Dave Hughes
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;  This program is free software: you can redistribute it and/or modify
;  it under the terms of the GNU General Public License as published by
;  the Free Software Foundation, either version 3 of the License, or
;  (at your option) any later version.  
;
;  This program is distributed in the hope that it will be useful,
;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;  GNU General Public License for more details.
; 
;  You should have received a copy of the GNU General Public License
;  along with this program.  If not, see <https://www.gnu.org/licenses/>. 
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

SECTION PAGE_36_MUSIC
defw 0 ; avoid song potentially placed at $0000, it could be mistaken with NULL
PUBLIC _song_revolution
_song_revolution:

; Next Revolution [HB], AKG format, v1.0.

; Generated by Arkos Tracker 2.

NextRevolutionHB_Start:
NextRevolutionHB_StartDisarkGenerateExternalLabel:

NextRevolutionHB_DisarkByteRegionStart0:
	defb "AT20"
NextRevolutionHB_DisarkPointerRegionStart1:
	defw NextRevolutionHB_ArpeggioTable	; The address of the Arpeggio table.
	defw NextRevolutionHB_PitchTable	; The address of the Pitch table.
	defw NextRevolutionHB_InstrumentTable	; The address of the Instrument table.
	defw NextRevolutionHB_EffectBlockTable	; The address of the Effect Block table.
NextRevolutionHB_DisarkPointerRegionEnd1:


; The addresses of each Subsong:
NextRevolutionHB_DisarkPointerRegionStart2:
	defw NextRevolutionHB_Subsong0_Start
NextRevolutionHB_DisarkPointerRegionEnd2:

; Declares all the Arpeggios.
NextRevolutionHB_ArpeggioTable:
NextRevolutionHB_DisarkPointerRegionStart3:
	defw NextRevolutionHB_Arpeggio1
	defw NextRevolutionHB_Arpeggio2
	defw NextRevolutionHB_Arpeggio3
	defw NextRevolutionHB_Arpeggio4
	defw NextRevolutionHB_Arpeggio5
	defw NextRevolutionHB_Arpeggio6
	defw NextRevolutionHB_Arpeggio7
	defw NextRevolutionHB_Arpeggio8
NextRevolutionHB_DisarkPointerRegionEnd3:

NextRevolutionHB_Arpeggio1:
	defb 1	; The speed.

	defb -5
	defb 0
	defb 3
	defb -128
NextRevolutionHB_DisarkWordForceReference4:
	defw NextRevolutionHB_Arpeggio1 + 0 + 1	; Loop.

NextRevolutionHB_Arpeggio2:
	defb 1	; The speed.

	defb -5
	defb 0
	defb 4
	defb -128
NextRevolutionHB_DisarkWordForceReference5:
	defw NextRevolutionHB_Arpeggio2 + 0 + 1	; Loop.

NextRevolutionHB_Arpeggio3:
	defb 1	; The speed.

	defb 0
	defb 3
	defb 7
	defb -128
NextRevolutionHB_DisarkWordForceReference6:
	defw NextRevolutionHB_Arpeggio3 + 0 + 1	; Loop.

NextRevolutionHB_Arpeggio4:
	defb 1	; The speed.

	defb 0
	defb 4
	defb 7
	defb -128
NextRevolutionHB_DisarkWordForceReference7:
	defw NextRevolutionHB_Arpeggio4 + 0 + 1	; Loop.

NextRevolutionHB_Arpeggio5:
	defb 1	; The speed.

	defb 3
	defb 7
	defb 12
	defb -128
NextRevolutionHB_DisarkWordForceReference8:
	defw NextRevolutionHB_Arpeggio5 + 0 + 1	; Loop.

NextRevolutionHB_Arpeggio6:
	defb 1	; The speed.

	defb 4
	defb 7
	defb 12
	defb -128
NextRevolutionHB_DisarkWordForceReference9:
	defw NextRevolutionHB_Arpeggio6 + 0 + 1	; Loop.

NextRevolutionHB_Arpeggio7:
	defb 1	; The speed.

	defb -5
	defb 0
	defb 5
	defb -128
NextRevolutionHB_DisarkWordForceReference10:
	defw NextRevolutionHB_Arpeggio7 + 0 + 1	; Loop.

NextRevolutionHB_Arpeggio8:
	defb 1	; The speed.

	defb -5
	defb 0
	defb 2
	defb -128
NextRevolutionHB_DisarkWordForceReference11:
	defw NextRevolutionHB_Arpeggio8 + 0 + 1	; Loop.

; Declares all the Pitches.
NextRevolutionHB_PitchTable:
NextRevolutionHB_DisarkPointerRegionStart12:
NextRevolutionHB_DisarkPointerRegionEnd12:

; Declares all the Instruments.
NextRevolutionHB_InstrumentTable:
NextRevolutionHB_DisarkPointerRegionStart13:
	defw NextRevolutionHB_EmptyInstrument
	defw NextRevolutionHB_Instrument1
	defw NextRevolutionHB_Instrument2
	defw NextRevolutionHB_Instrument3
	defw NextRevolutionHB_Instrument4
	defw NextRevolutionHB_Instrument5
	defw NextRevolutionHB_Instrument6
	defw NextRevolutionHB_Instrument7
NextRevolutionHB_DisarkPointerRegionEnd13:

NextRevolutionHB_EmptyInstrument:
	defb 0	; The speed (>0, 0 for 256).
NextRevolutionHB_EmptyInstrument_Loop:	defb 0	; No Soft no Hard. Volume: 0. Noise? false.

	defb 6	; Loop to silence.

NextRevolutionHB_Instrument1:
	defb 1	; The speed (>0, 0 for 256).
	defb 249	; Soft only. Volume: 15. Volume only.

	defb 241	; Soft only. Volume: 14. Volume only.

	defb 233	; Soft only. Volume: 13. Volume only.

	defb 225	; Soft only. Volume: 12. Volume only.

	defb 217	; Soft only. Volume: 11. Volume only.

	defb 209	; Soft only. Volume: 10. Volume only.

	defb 201	; Soft only. Volume: 9. Volume only.

	defb 193	; Soft only. Volume: 8. Volume only.

	defb 185	; Soft only. Volume: 7. Volume only.

	defb 177	; Soft only. Volume: 6. Volume only.

	defb 169	; Soft only. Volume: 5. Volume only.

	defb 161	; Soft only. Volume: 4. Volume only.

	defb 153	; Soft only. Volume: 3. Volume only.

	defb 145	; Soft only. Volume: 2. Volume only.

	defb 137	; Soft only. Volume: 1. Volume only.

	defb 6	; Loop to silence.

NextRevolutionHB_Instrument2:
	defb 1	; The speed (>0, 0 for 256).
	defb 248	; No Soft no Hard. Volume: 15. Noise? true.
	defb 1	; Noise: 1.

	defb 113	; Soft only. Volume: 14.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 150	; Pitch.

	defb 105	; Soft only. Volume: 13.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 300	; Pitch.

	defb 97	; Soft only. Volume: 12.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 400	; Pitch.

	defb 89	; Soft only. Volume: 11.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 500	; Pitch.

	defb 81	; Soft only. Volume: 10.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 600	; Pitch.

	defb 6	; Loop to silence.

NextRevolutionHB_Instrument3:
	defb 1	; The speed (>0, 0 for 256).
	defb 248	; No Soft no Hard. Volume: 15. Noise? true.
	defb 1	; Noise: 1.

	defb 113	; Soft only. Volume: 14.
	defb 34	; Additional data. Noise: 2. Pitch? true. Arp? false. Period? false.
	defw -10	; Pitch.

	defb 97	; Soft only. Volume: 12.
	defb 35	; Additional data. Noise: 3. Pitch? true. Arp? false. Period? false.
	defw -30	; Pitch.

	defb 216	; No Soft no Hard. Volume: 11. Noise? true.
	defb 1	; Noise: 1.

	defb 80	; No Soft no Hard. Volume: 10. Noise? false.

	defb 208	; No Soft no Hard. Volume: 10. Noise? true.
	defb 1	; Noise: 1.

	defb 200	; No Soft no Hard. Volume: 9. Noise? true.
	defb 1	; Noise: 1.

	defb 192	; No Soft no Hard. Volume: 8. Noise? true.
	defb 1	; Noise: 1.

	defb 184	; No Soft no Hard. Volume: 7. Noise? true.
	defb 1	; Noise: 1.

	defb 176	; No Soft no Hard. Volume: 6. Noise? true.
	defb 1	; Noise: 1.

	defb 168	; No Soft no Hard. Volume: 5. Noise? true.
	defb 1	; Noise: 1.

	defb 160	; No Soft no Hard. Volume: 4. Noise? true.
	defb 1	; Noise: 1.

	defb 144	; No Soft no Hard. Volume: 2. Noise? true.
	defb 1	; Noise: 1.

	defb 136	; No Soft no Hard. Volume: 1. Noise? true.
	defb 1	; Noise: 1.

	defb 6	; Loop to silence.

NextRevolutionHB_Instrument4:
	defb 4	; The speed (>0, 0 for 256).
	defb 249	; Soft only. Volume: 15. Volume only.

	defb 233	; Soft only. Volume: 13. Volume only.

	defb 217	; Soft only. Volume: 11. Volume only.

	defb 209	; Soft only. Volume: 10. Volume only.

	defb 201	; Soft only. Volume: 9. Volume only.

	defb 193	; Soft only. Volume: 8. Volume only.

	defb 185	; Soft only. Volume: 7. Volume only.

	defb 177	; Soft only. Volume: 6. Volume only.

	defb 169	; Soft only. Volume: 5. Volume only.

	defb 161	; Soft only. Volume: 4. Volume only.

	defb 153	; Soft only. Volume: 3. Volume only.

	defb 145	; Soft only. Volume: 2. Volume only.

	defb 137	; Soft only. Volume: 1. Volume only.

	defb 6	; Loop to silence.

NextRevolutionHB_Instrument5:
	defb 1	; The speed (>0, 0 for 256).
	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 6	; Loop to silence.

NextRevolutionHB_Instrument6:
	defb 1	; The speed (>0, 0 for 256).
	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 6	; Loop to silence.

NextRevolutionHB_Instrument7:
	defb 1	; The speed (>0, 0 for 256).
	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 131	; Hard only. Envelope: 8. Retrig? false. Simple configuration.

	defb 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
NextRevolutionHB_EffectBlockTable:
NextRevolutionHB_DisarkPointerRegionStart14:
	defw NextRevolutionHB_EffectBlock_P8	; Index 0
	defw NextRevolutionHB_EffectBlock_P5P1P7P2P30P5	; Index 1
	defw NextRevolutionHB_EffectBlock_P6P1	; Index 2
	defw NextRevolutionHB_EffectBlock_P6P5	; Index 3
	defw NextRevolutionHB_EffectBlock_P7P5P30P5	; Index 4
	defw NextRevolutionHB_EffectBlock_P6P3	; Index 5
	defw NextRevolutionHB_EffectBlock_P6P6	; Index 6
	defw NextRevolutionHB_EffectBlock_P4P0	; Index 7
	defw NextRevolutionHB_EffectBlock_P6P0	; Index 8
	defw NextRevolutionHB_EffectBlock_P6P2	; Index 9
	defw NextRevolutionHB_EffectBlock_P30P5	; Index 10
	defw NextRevolutionHB_EffectBlock_P6P7	; Index 11
	defw NextRevolutionHB_EffectBlock_P7P4P30P5	; Index 12
	defw NextRevolutionHB_EffectBlock_P7P2P30P5	; Index 13
	defw NextRevolutionHB_EffectBlock_P7P3P30P5	; Index 14
NextRevolutionHB_DisarkPointerRegionEnd14:

NextRevolutionHB_EffectBlock_P8:
	defb 8
NextRevolutionHB_EffectBlock_P4P0:
	defb 4, 0
NextRevolutionHB_EffectBlock_P6P0:
	defb 6, 0
NextRevolutionHB_EffectBlock_P6P1:
	defb 6, 1
NextRevolutionHB_EffectBlock_P6P2:
	defb 6, 2
NextRevolutionHB_EffectBlock_P6P3:
	defb 6, 3
NextRevolutionHB_EffectBlock_P6P5:
	defb 6, 5
NextRevolutionHB_EffectBlock_P6P6:
	defb 6, 6
NextRevolutionHB_EffectBlock_P6P7:
	defb 6, 7
NextRevolutionHB_EffectBlock_P7P4P30P5:
	defb 7, 4, 30, 5
NextRevolutionHB_EffectBlock_P7P2P30P5:
	defb 7, 2, 30, 5
NextRevolutionHB_EffectBlock_P5P1P7P2P30P5:
	defb 5, 1, 7, 2, 30, 5
NextRevolutionHB_EffectBlock_P7P5P30P5:
	defb 7, 5, 30, 5
NextRevolutionHB_EffectBlock_P7P3P30P5:
	defb 7, 3, 30, 5
NextRevolutionHB_EffectBlock_P30P5:
	defb 30, 5

NextRevolutionHB_DisarkByteRegionEnd0:

; Subsong 0
; ----------------------
NextRevolutionHB_Subsong0_DisarkByteRegionStart0:
NextRevolutionHB_Subsong0_Start:
	defb 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	defb 1	; Digichannel (0-2).
	defb 1	; PSG count (>0).
	defb 3	; Loop start index (>=0).
	defb 9	; End index (>=0).
	defb 6	; Initial speed (>=0).
	defb 24	; Base note index (>=0).

NextRevolutionHB_Subsong0_Linker:
NextRevolutionHB_Subsong0_DisarkPointerRegionStart1:
; Position 0
	defw NextRevolutionHB_Subsong0_Track0
	defw NextRevolutionHB_Subsong0_Track1
	defw NextRevolutionHB_Subsong0_Track2
	defw NextRevolutionHB_Subsong0_LinkerBlock0

; Position 1
	defw NextRevolutionHB_Subsong0_Track3
	defw NextRevolutionHB_Subsong0_Track4
	defw NextRevolutionHB_Subsong0_Track5
	defw NextRevolutionHB_Subsong0_LinkerBlock0

; Position 2
	defw NextRevolutionHB_Subsong0_Track16
	defw NextRevolutionHB_Subsong0_Track6
	defw NextRevolutionHB_Subsong0_Track7
	defw NextRevolutionHB_Subsong0_LinkerBlock1

; Position 3
NextRevolutionHB_Subsong0_Linker_Loop:
	defw NextRevolutionHB_Subsong0_Track8
	defw NextRevolutionHB_Subsong0_Track9
	defw NextRevolutionHB_Subsong0_Track10
	defw NextRevolutionHB_Subsong0_LinkerBlock0

; Position 4
	defw NextRevolutionHB_Subsong0_Track11
	defw NextRevolutionHB_Subsong0_Track12
	defw NextRevolutionHB_Subsong0_Track13
	defw NextRevolutionHB_Subsong0_LinkerBlock0

; Position 5
	defw NextRevolutionHB_Subsong0_Track3
	defw NextRevolutionHB_Subsong0_Track14
	defw NextRevolutionHB_Subsong0_Track15
	defw NextRevolutionHB_Subsong0_LinkerBlock0

; Position 6
	defw NextRevolutionHB_Subsong0_Track3
	defw NextRevolutionHB_Subsong0_Track17
	defw NextRevolutionHB_Subsong0_Track18
	defw NextRevolutionHB_Subsong0_LinkerBlock2

; Position 7
	defw NextRevolutionHB_Subsong0_Track3
	defw NextRevolutionHB_Subsong0_Track19
	defw NextRevolutionHB_Subsong0_Track20
	defw NextRevolutionHB_Subsong0_LinkerBlock3

; Position 8
	defw NextRevolutionHB_Subsong0_Track3
	defw NextRevolutionHB_Subsong0_Track21
	defw NextRevolutionHB_Subsong0_Track20
	defw NextRevolutionHB_Subsong0_LinkerBlock0

; Position 9
	defw NextRevolutionHB_Subsong0_Track16
	defw NextRevolutionHB_Subsong0_Track6
	defw NextRevolutionHB_Subsong0_Track22
	defw NextRevolutionHB_Subsong0_LinkerBlock1

NextRevolutionHB_Subsong0_DisarkPointerRegionEnd1:
	defw 0	; Loop.
NextRevolutionHB_Subsong0_DisarkWordForceReference2:
	defw NextRevolutionHB_Subsong0_Linker_Loop

NextRevolutionHB_Subsong0_LinkerBlock0:
	defb 64	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
NextRevolutionHB_Subsong0_DisarkWordForceReference3:
	defw NextRevolutionHB_Subsong0_SpeedTrack0	; SpeedTrack address.
NextRevolutionHB_Subsong0_DisarkWordForceReference4:
	defw NextRevolutionHB_Subsong0_EventTrack0	; EventTrack address.
NextRevolutionHB_Subsong0_LinkerBlock1:
	defb 80	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
NextRevolutionHB_Subsong0_DisarkWordForceReference5:
	defw NextRevolutionHB_Subsong0_SpeedTrack0	; SpeedTrack address.
NextRevolutionHB_Subsong0_DisarkWordForceReference6:
	defw NextRevolutionHB_Subsong0_EventTrack0	; EventTrack address.
NextRevolutionHB_Subsong0_LinkerBlock2:
	defb 96	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
NextRevolutionHB_Subsong0_DisarkWordForceReference7:
	defw NextRevolutionHB_Subsong0_SpeedTrack0	; SpeedTrack address.
NextRevolutionHB_Subsong0_DisarkWordForceReference8:
	defw NextRevolutionHB_Subsong0_EventTrack0	; EventTrack address.
NextRevolutionHB_Subsong0_LinkerBlock3:
	defb 32	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
NextRevolutionHB_Subsong0_DisarkWordForceReference9:
	defw NextRevolutionHB_Subsong0_SpeedTrack0	; SpeedTrack address.
NextRevolutionHB_Subsong0_DisarkWordForceReference10:
	defw NextRevolutionHB_Subsong0_EventTrack0	; EventTrack address.

NextRevolutionHB_Subsong0_Track0:
	defb 61, 31	; Waits for 32 lines.

	defb 144
	defb 3	; New Instrument (3).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track1:
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track2:
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 220
	defb 4	; New Instrument (4).
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 28
	defb 60	; Waits for 1 line.

	defb 28
	defb 60	; Waits for 1 line.

	defb 92
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 92
	defb 2	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 87
	defb 1	; Index to an effect block.
	defb 61, 15	; Waits for 16 lines.

	defb 124	; No note, but effects.
	defb 7	; Index to an effect block.
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 92
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 28
	defb 60	; Waits for 1 line.

	defb 28
	defb 60	; Waits for 1 line.

	defb 92
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 92
	defb 2	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 87
	defb 1	; Index to an effect block.
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 87
	defb 7	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 23
	defb 60	; Waits for 1 line.

	defb 23
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track3:
	defb 144
	defb 3	; New Instrument (3).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track4:
	defb 168
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 40
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 40
	defb 60	; Waits for 1 line.

	defb 45
	defb 60	; Waits for 1 line.

	defb 40
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 175
	defb 6	; New Instrument (6).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 175
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 177
	defb 6	; New Instrument (6).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 178
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 50
	defb 60	; Waits for 1 line.

	defb 51
	defb 60	; Waits for 1 line.

	defb 180
	defb 6	; New Instrument (6).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 168
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 40
	defb 60	; Waits for 1 line.

	defb 45
	defb 60	; Waits for 1 line.

	defb 40
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 175
	defb 6	; New Instrument (6).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 175
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 177
	defb 6	; New Instrument (6).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 178
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 50
	defb 60	; Waits for 1 line.

	defb 47
	defb 60	; Waits for 1 line.

	defb 50
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track5:
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 220
	defb 4	; New Instrument (4).
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 28
	defb 60	; Waits for 1 line.

	defb 28
	defb 60	; Waits for 1 line.

	defb 92
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 92
	defb 2	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 87
	defb 1	; Index to an effect block.
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 87
	defb 7	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 23
	defb 60	; Waits for 1 line.

	defb 23
	defb 61, 6	; Waits for 7 lines.

	defb 92
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 28
	defb 60	; Waits for 1 line.

	defb 28
	defb 60	; Waits for 1 line.

	defb 92
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 92
	defb 2	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 87
	defb 1	; Index to an effect block.
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 87
	defb 7	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 23
	defb 60	; Waits for 1 line.

	defb 23
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track6:
	defb 177
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 50
	defb 60	; Waits for 1 line.

	defb 50
	defb 60	; Waits for 1 line.

	defb 50
	defb 60	; Waits for 1 line.

	defb 50
	defb 60	; Waits for 1 line.

	defb 50
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 47
	defb 60	; Waits for 1 line.

	defb 40
	defb 60	; Waits for 1 line.

	defb 45
	defb 60	; Waits for 1 line.

	defb 45
	defb 60	; Waits for 1 line.

	defb 45
	defb 60	; Waits for 1 line.

	defb 40
	defb 60	; Waits for 1 line.

	defb 43
	defb 60	; Waits for 1 line.

	defb 43
	defb 60	; Waits for 1 line.

	defb 43
	defb 60	; Waits for 1 line.

	defb 43
	defb 60	; Waits for 1 line.

	defb 168
	defb 6	; New Instrument (6).
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track7:
	defb 217
	defb 1	; New Instrument (1).
	defb 13	; Index to an effect block.
	defb 61, 14	; Waits for 15 lines.

	defb 90
	defb 14	; Index to an effect block.
	defb 61, 14	; Waits for 15 lines.

	defb 85
	defb 4	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 83
	defb 10	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 80
	defb 10	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track8:
	defb 128
	defb 2	; New Instrument (2).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 144
	defb 3	; New Instrument (3).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 144
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 0
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 144
	defb 3	; New Instrument (3).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 144
	defb 3	; New Instrument (3).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 128
	defb 2	; New Instrument (2).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 144
	defb 3	; New Instrument (3).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 144
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 0
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 144
	defb 3	; New Instrument (3).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 144
	defb 3	; New Instrument (3).
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track9:
	defb 180
	defb 7	; New Instrument (7).
	defb 61, 8	; Waits for 9 lines.

	defb 173
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 175
	defb 7	; New Instrument (7).
	defb 61, 10	; Waits for 11 lines.

	defb 173
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 170
	defb 7	; New Instrument (7).
	defb 61, 10	; Waits for 11 lines.

	defb 172
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 45
	defb 60	; Waits for 1 line.

	defb 178
	defb 7	; New Instrument (7).
	defb 61, 8	; Waits for 9 lines.

	defb 173
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 170
	defb 7	; New Instrument (7).
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track10:
	defb 220
	defb 4	; New Instrument (4).
	defb 2	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 99
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 35
	defb 60	; Waits for 1 line.

	defb 35
	defb 60	; Waits for 1 line.

	defb 87
	defb 3	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 97
	defb 0	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 32
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 30
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 33
	defb 60	; Waits for 1 line.

	defb 94
	defb 8	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 97
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 33
	defb 60	; Waits for 1 line.

	defb 33
	defb 60	; Waits for 1 line.

	defb 90
	defb 5	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 96
	defb 0	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 28
	defb 60	; Waits for 1 line.

	defb 85
	defb 5	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 89
	defb 0	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 23
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track11:
	defb 128
	defb 2	; New Instrument (2).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 144
	defb 3	; New Instrument (3).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 144
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 0
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 144
	defb 3	; New Instrument (3).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 144
	defb 3	; New Instrument (3).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 191
	defb 12	; Escape note (12).
	defb 2	; New Instrument (2).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 144
	defb 3	; New Instrument (3).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 144
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 0
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 144
	defb 3	; New Instrument (3).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 144
	defb 3	; New Instrument (3).
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track12:
	defb 168
	defb 7	; New Instrument (7).
	defb 61, 8	; Waits for 9 lines.

	defb 172
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 45
	defb 60	; Waits for 1 line.

	defb 175
	defb 7	; New Instrument (7).
	defb 61, 10	; Waits for 11 lines.

	defb 173
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 170
	defb 7	; New Instrument (7).
	defb 61, 10	; Waits for 11 lines.

	defb 172
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 45
	defb 60	; Waits for 1 line.

	defb 178
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 178
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 50
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 45
	defb 60	; Waits for 1 line.

	defb 45
	defb 60	; Waits for 1 line.

	defb 173
	defb 7	; New Instrument (7).
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track13:
	defb 220
	defb 4	; New Instrument (4).
	defb 2	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 99
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 35
	defb 60	; Waits for 1 line.

	defb 35
	defb 60	; Waits for 1 line.

	defb 87
	defb 3	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 97
	defb 0	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 32
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 30
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 33
	defb 60	; Waits for 1 line.

	defb 85
	defb 3	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 97
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 33
	defb 60	; Waits for 1 line.

	defb 33
	defb 60	; Waits for 1 line.

	defb 90
	defb 5	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 96
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 28
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 85
	defb 3	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 89
	defb 9	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track14:
	defb 177
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 179
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 180
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 52
	defb 60	; Waits for 1 line.

	defb 63
	defb 80	; Escape note (80).
	defb 60	; Waits for 1 line.

	defb 182
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 182
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 180
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 179
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 51
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 178
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 178
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 177
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 175
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 47
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 173
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 173
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 172
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 170
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 42
	defb 60	; Waits for 1 line.

	defb 168
	defb 7	; New Instrument (7).
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track15:
	defb 217
	defb 4	; New Instrument (4).
	defb 9	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 104
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 39
	defb 60	; Waits for 1 line.

	defb 82
	defb 3	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 94
	defb 5	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 101
	defb 0	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 37
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 90
	defb 3	; Index to an effect block.
	defb 61, 14	; Waits for 15 lines.

	defb 21
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track16:
	defb 144
	defb 3	; New Instrument (3).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 60	; Waits for 1 line.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 144
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 144
	defb 3	; New Instrument (3).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 16
	defb 60	; Waits for 1 line.

	defb 128
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 144
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 128
	defb 2	; New Instrument (2).
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track17:
	defb 177
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 179
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 180
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 52
	defb 60	; Waits for 1 line.

	defb 63
	defb 80	; Escape note (80).
	defb 60	; Waits for 1 line.

	defb 182
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 182
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 180
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 179
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 51
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 178
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 178
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 54
	defb 60	; Waits for 1 line.

	defb 55
	defb 60	; Waits for 1 line.

	defb 54
	defb 60	; Waits for 1 line.

	defb 50
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 178
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 178
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 54
	defb 60	; Waits for 1 line.

	defb 55
	defb 60	; Waits for 1 line.

	defb 54
	defb 60	; Waits for 1 line.

	defb 178
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 47
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 175
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 51
	defb 60	; Waits for 1 line.

	defb 52
	defb 60	; Waits for 1 line.

	defb 51
	defb 60	; Waits for 1 line.

	defb 47
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 175
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 175
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 51
	defb 60	; Waits for 1 line.

	defb 52
	defb 60	; Waits for 1 line.

	defb 51
	defb 60	; Waits for 1 line.

	defb 47
	defb 60	; Waits for 1 line.

	defb 175
	defb 7	; New Instrument (7).
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track18:
	defb 217
	defb 4	; New Instrument (4).
	defb 9	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 104
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 39
	defb 60	; Waits for 1 line.

	defb 94
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 94
	defb 5	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 101
	defb 0	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 37
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 37
	defb 60	; Waits for 1 line.

	defb 90
	defb 3	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 101
	defb 0	; Index to an effect block.
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 37
	defb 60	; Waits for 1 line.

	defb 90
	defb 3	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 101
	defb 0	; Index to an effect block.
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 37
	defb 60	; Waits for 1 line.

	defb 99
	defb 6	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 103
	defb 0	; Index to an effect block.
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 39
	defb 60	; Waits for 1 line.

	defb 99
	defb 6	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 103
	defb 0	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track19:
	defb 168
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 40
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 40
	defb 60	; Waits for 1 line.

	defb 45
	defb 60	; Waits for 1 line.

	defb 40
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 175
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 175
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 177
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 178
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 50
	defb 60	; Waits for 1 line.

	defb 51
	defb 60	; Waits for 1 line.

	defb 180
	defb 7	; New Instrument (7).
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track20:
	defb 220
	defb 4	; New Instrument (4).
	defb 5	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 104
	defb 0	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 60	; Waits for 1 line.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 38
	defb 60	; Waits for 1 line.

	defb 99
	defb 8	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 99
	defb 11	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 99
	defb 0	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 33
	defb 60	; Waits for 1 line.

	defb 37
	defb 60	; Waits for 1 line.

	defb 35
	defb 60	; Waits for 1 line.

	defb 92
	defb 5	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 104
	defb 0	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 40
	defb 60	; Waits for 1 line.

	defb 40
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 38
	defb 60	; Waits for 1 line.

	defb 99
	defb 8	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 99
	defb 11	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 99
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 35
	defb 60	; Waits for 1 line.

	defb 35
	defb 60	; Waits for 1 line.

	defb 36
	defb 60	; Waits for 1 line.

	defb 37
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track21:
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 168
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 40
	defb 60	; Waits for 1 line.

	defb 45
	defb 60	; Waits for 1 line.

	defb 40
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 175
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 175
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 177
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 178
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 50
	defb 60	; Waits for 1 line.

	defb 51
	defb 60	; Waits for 1 line.

	defb 180
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 168
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 40
	defb 60	; Waits for 1 line.

	defb 45
	defb 60	; Waits for 1 line.

	defb 40
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 175
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 175
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 177
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 178
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 50
	defb 60	; Waits for 1 line.

	defb 47
	defb 60	; Waits for 1 line.

	defb 178
	defb 7	; New Instrument (7).
	defb 61, 127	; Waits for 128 lines.


NextRevolutionHB_Subsong0_Track22:
	defb 217
	defb 1	; New Instrument (1).
	defb 12	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 229
	defb 4	; New Instrument (4).
	defb 0	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 37
	defb 60	; Waits for 1 line.

	defb 37
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 38
	defb 60	; Waits for 1 line.

	defb 218
	defb 1	; New Instrument (1).
	defb 4	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 225
	defb 4	; New Instrument (4).
	defb 0	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 85
	defb 4	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 21
	defb 60	; Waits for 1 line.

	defb 21
	defb 60	; Waits for 1 line.

	defb 92
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 83
	defb 4	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 19
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 208
	defb 1	; New Instrument (1).
	defb 10	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


; The speed tracks
NextRevolutionHB_Subsong0_SpeedTrack0:
	defb 10	; Value: 5.
	defb 253	; Wait for 127 lines.

; The event tracks
NextRevolutionHB_Subsong0_EventTrack0:
	defb 255	; Wait for 128 lines.

NextRevolutionHB_Subsong0_DisarkByteRegionEnd0:
