; Lonely Road [HB], AKG format, v1.0.

; Generated by Arkos Tracker 2.

LonelyRoadHB_Start:
LonelyRoadHB_StartDisarkGenerateExternalLabel:

LonelyRoadHB_DisarkByteRegionStart0:
	defb "AT20"
LonelyRoadHB_DisarkPointerRegionStart1:
	defw LonelyRoadHB_ArpeggioTable	; The address of the Arpeggio table.
	defw LonelyRoadHB_PitchTable	; The address of the Pitch table.
	defw LonelyRoadHB_InstrumentTable	; The address of the Instrument table.
	defw LonelyRoadHB_EffectBlockTable	; The address of the Effect Block table.
LonelyRoadHB_DisarkPointerRegionEnd1:


; The addresses of each Subsong:
LonelyRoadHB_DisarkPointerRegionStart2:
	defw LonelyRoadHB_Subsong0_Start
LonelyRoadHB_DisarkPointerRegionEnd2:

; Declares all the Arpeggios.
LonelyRoadHB_ArpeggioTable:
LonelyRoadHB_DisarkPointerRegionStart3:
	defw LonelyRoadHB_Arpeggio1
	defw LonelyRoadHB_Arpeggio2
	defw LonelyRoadHB_Arpeggio3
	defw LonelyRoadHB_Arpeggio4
	defw LonelyRoadHB_Arpeggio5
	defw LonelyRoadHB_Arpeggio6
LonelyRoadHB_DisarkPointerRegionEnd3:

LonelyRoadHB_Arpeggio1:
	defb 1	; The speed.

	defb 4
	defb 7
	defb 12
	defb -128
LonelyRoadHB_DisarkWordForceReference4:
	defw LonelyRoadHB_Arpeggio1 + 0 + 1	; Loop.

LonelyRoadHB_Arpeggio2:
	defb 1	; The speed.

	defb -5
	defb 0
	defb 4
	defb -128
LonelyRoadHB_DisarkWordForceReference5:
	defw LonelyRoadHB_Arpeggio2 + 0 + 1	; Loop.

LonelyRoadHB_Arpeggio3:
	defb 1	; The speed.

	defb 0
	defb 4
	defb 7
	defb -128
LonelyRoadHB_DisarkWordForceReference6:
	defw LonelyRoadHB_Arpeggio3 + 0 + 1	; Loop.

LonelyRoadHB_Arpeggio4:
	defb 1	; The speed.

	defb 3
	defb 7
	defb 12
	defb -128
LonelyRoadHB_DisarkWordForceReference7:
	defw LonelyRoadHB_Arpeggio4 + 0 + 1	; Loop.

LonelyRoadHB_Arpeggio5:
	defb 1	; The speed.

	defb 0
	defb 3
	defb 7
	defb -128
LonelyRoadHB_DisarkWordForceReference8:
	defw LonelyRoadHB_Arpeggio5 + 0 + 1	; Loop.

LonelyRoadHB_Arpeggio6:
	defb 1	; The speed.

	defb -5
	defb 0
	defb 3
	defb -128
LonelyRoadHB_DisarkWordForceReference9:
	defw LonelyRoadHB_Arpeggio6 + 0 + 1	; Loop.

; Declares all the Pitches.
LonelyRoadHB_PitchTable:
LonelyRoadHB_DisarkPointerRegionStart10:
LonelyRoadHB_DisarkPointerRegionEnd10:

; Declares all the Instruments.
LonelyRoadHB_InstrumentTable:
LonelyRoadHB_DisarkPointerRegionStart11:
	defw LonelyRoadHB_EmptyInstrument
	defw LonelyRoadHB_Instrument1
	defw LonelyRoadHB_Instrument2
	defw LonelyRoadHB_Instrument3
	defw LonelyRoadHB_Instrument4
	defw LonelyRoadHB_Instrument5
	defw LonelyRoadHB_Instrument6
	defw LonelyRoadHB_Instrument7
	defw LonelyRoadHB_Instrument8
LonelyRoadHB_DisarkPointerRegionEnd11:

LonelyRoadHB_EmptyInstrument:
	defb 0	; The speed (>0, 0 for 256).
LonelyRoadHB_EmptyInstrument_Loop:	defb 0	; No Soft no Hard. Volume: 0. Noise? false.

	defb 6	; Loop to silence.

LonelyRoadHB_Instrument1:
	defb 1	; The speed (>0, 0 for 256).
	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 6	; Loop to silence.

LonelyRoadHB_Instrument2:
	defb 1	; The speed (>0, 0 for 256).
	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 3	; Hard only. Envelope: 8. Retrig? false. Not simple configuration.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 48	; Arpeggio.

	defb 6	; Loop to silence.

LonelyRoadHB_Instrument3:
	defb 1	; The speed (>0, 0 for 256).
	defb 248	; No Soft no Hard. Volume: 15. Noise? true.
	defb 1	; Noise: 1.

	defb 113	; Soft only. Volume: 14.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 150	; Pitch.

	defb 105	; Soft only. Volume: 13.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 300	; Pitch.

	defb 97	; Soft only. Volume: 12.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 400	; Pitch.

	defb 89	; Soft only. Volume: 11.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 500	; Pitch.

	defb 81	; Soft only. Volume: 10.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 600	; Pitch.

	defb 6	; Loop to silence.

LonelyRoadHB_Instrument4:
	defb 1	; The speed (>0, 0 for 256).
	defb 248	; No Soft no Hard. Volume: 15. Noise? true.
	defb 1	; Noise: 1.

	defb 113	; Soft only. Volume: 14.
	defb 34	; Additional data. Noise: 2. Pitch? true. Arp? false. Period? false.
	defw -10	; Pitch.

	defb 97	; Soft only. Volume: 12.
	defb 35	; Additional data. Noise: 3. Pitch? true. Arp? false. Period? false.
	defw -30	; Pitch.

	defb 216	; No Soft no Hard. Volume: 11. Noise? true.
	defb 1	; Noise: 1.

	defb 80	; No Soft no Hard. Volume: 10. Noise? false.

	defb 208	; No Soft no Hard. Volume: 10. Noise? true.
	defb 1	; Noise: 1.

	defb 200	; No Soft no Hard. Volume: 9. Noise? true.
	defb 1	; Noise: 1.

	defb 192	; No Soft no Hard. Volume: 8. Noise? true.
	defb 1	; Noise: 1.

	defb 184	; No Soft no Hard. Volume: 7. Noise? true.
	defb 1	; Noise: 1.

	defb 176	; No Soft no Hard. Volume: 6. Noise? true.
	defb 1	; Noise: 1.

	defb 168	; No Soft no Hard. Volume: 5. Noise? true.
	defb 1	; Noise: 1.

	defb 160	; No Soft no Hard. Volume: 4. Noise? true.
	defb 1	; Noise: 1.

	defb 144	; No Soft no Hard. Volume: 2. Noise? true.
	defb 1	; Noise: 1.

	defb 136	; No Soft no Hard. Volume: 1. Noise? true.
	defb 1	; Noise: 1.

	defb 6	; Loop to silence.

LonelyRoadHB_Instrument5:
	defb 1	; The speed (>0, 0 for 256).
	defb 224	; No Soft no Hard. Volume: 12. Noise? true.
	defb 1	; Noise: 1.

	defb 208	; No Soft no Hard. Volume: 10. Noise? true.
	defb 1	; Noise: 1.

	defb 192	; No Soft no Hard. Volume: 8. Noise? true.
	defb 1	; Noise: 1.

	defb 168	; No Soft no Hard. Volume: 5. Noise? true.
	defb 1	; Noise: 1.

	defb 144	; No Soft no Hard. Volume: 2. Noise? true.
	defb 1	; Noise: 1.

	defb 6	; Loop to silence.

LonelyRoadHB_Instrument6:
	defb 1	; The speed (>0, 0 for 256).
	defb 249	; Soft only. Volume: 15. Volume only.

	defb 241	; Soft only. Volume: 14. Volume only.

	defb 233	; Soft only. Volume: 13. Volume only.

	defb 225	; Soft only. Volume: 12. Volume only.

	defb 217	; Soft only. Volume: 11. Volume only.

	defb 209	; Soft only. Volume: 10. Volume only.

	defb 201	; Soft only. Volume: 9. Volume only.

	defb 193	; Soft only. Volume: 8. Volume only.

	defb 185	; Soft only. Volume: 7. Volume only.

	defb 177	; Soft only. Volume: 6. Volume only.

	defb 169	; Soft only. Volume: 5. Volume only.

	defb 161	; Soft only. Volume: 4. Volume only.

	defb 153	; Soft only. Volume: 3. Volume only.

	defb 145	; Soft only. Volume: 2. Volume only.

	defb 137	; Soft only. Volume: 1. Volume only.

	defb 6	; Loop to silence.

LonelyRoadHB_Instrument7:
	defb 1	; The speed (>0, 0 for 256).
	defb 249	; Soft only. Volume: 15. Volume only.

	defb 113	; Soft only. Volume: 14.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 233	; Soft only. Volume: 13. Volume only.

	defb 97	; Soft only. Volume: 12.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 217	; Soft only. Volume: 11. Volume only.

	defb 81	; Soft only. Volume: 10.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 201	; Soft only. Volume: 9. Volume only.

	defb 65	; Soft only. Volume: 8.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 185	; Soft only. Volume: 7. Volume only.

	defb 49	; Soft only. Volume: 6.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 169	; Soft only. Volume: 5. Volume only.

	defb 33	; Soft only. Volume: 4.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 153	; Soft only. Volume: 3. Volume only.

	defb 17	; Soft only. Volume: 2.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 3	; Arpeggio.

	defb 137	; Soft only. Volume: 1. Volume only.

	defb 6	; Loop to silence.

LonelyRoadHB_Instrument8:
	defb 1	; The speed (>0, 0 for 256).
	defb 249	; Soft only. Volume: 15. Volume only.

	defb 113	; Soft only. Volume: 14.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 233	; Soft only. Volume: 13. Volume only.

	defb 97	; Soft only. Volume: 12.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 217	; Soft only. Volume: 11. Volume only.

	defb 81	; Soft only. Volume: 10.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 201	; Soft only. Volume: 9. Volume only.

	defb 65	; Soft only. Volume: 8.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 185	; Soft only. Volume: 7. Volume only.

	defb 49	; Soft only. Volume: 6.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 169	; Soft only. Volume: 5. Volume only.

	defb 33	; Soft only. Volume: 4.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 153	; Soft only. Volume: 3. Volume only.

	defb 17	; Soft only. Volume: 2.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 4	; Arpeggio.

	defb 137	; Soft only. Volume: 1. Volume only.

	defb 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
LonelyRoadHB_EffectBlockTable:
LonelyRoadHB_DisarkPointerRegionStart12:
	defw LonelyRoadHB_EffectBlock_P6P0	; Index 0
	defw LonelyRoadHB_EffectBlock_P6P1	; Index 1
	defw LonelyRoadHB_EffectBlock_P6P4	; Index 2
	defw LonelyRoadHB_EffectBlock_P6P3	; Index 3
	defw LonelyRoadHB_EffectBlock_P8	; Index 4
	defw LonelyRoadHB_EffectBlock_P6P2	; Index 5
	defw LonelyRoadHB_EffectBlock_P6P5	; Index 6
LonelyRoadHB_DisarkPointerRegionEnd12:

LonelyRoadHB_EffectBlock_P8:
	defb 8
LonelyRoadHB_EffectBlock_P6P0:
	defb 6, 0
LonelyRoadHB_EffectBlock_P6P1:
	defb 6, 1
LonelyRoadHB_EffectBlock_P6P2:
	defb 6, 2
LonelyRoadHB_EffectBlock_P6P3:
	defb 6, 3
LonelyRoadHB_EffectBlock_P6P4:
	defb 6, 4
LonelyRoadHB_EffectBlock_P6P5:
	defb 6, 5

LonelyRoadHB_DisarkByteRegionEnd0:

; Subsong 0
; ----------------------
LonelyRoadHB_Subsong0_DisarkByteRegionStart0:
LonelyRoadHB_Subsong0_Start:
	defb 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	defb 0	; Digichannel (0-2).
	defb 1	; PSG count (>0).
	defb 3	; Loop start index (>=0).
	defb 14	; End index (>=0).
	defb 6	; Initial speed (>=0).
	defb 4	; Base note index (>=0).

LonelyRoadHB_Subsong0_Linker:
LonelyRoadHB_Subsong0_DisarkPointerRegionStart1:
; Position 0
	defw LonelyRoadHB_Subsong0_Track3
	defw LonelyRoadHB_Subsong0_Track0
	defw LonelyRoadHB_Subsong0_Track3
	defw LonelyRoadHB_Subsong0_LinkerBlock0

; Position 1
	defw LonelyRoadHB_Subsong0_Track1
	defw LonelyRoadHB_Subsong0_Track2
	defw LonelyRoadHB_Subsong0_Track3
	defw LonelyRoadHB_Subsong0_LinkerBlock1

; Position 2
	defw LonelyRoadHB_Subsong0_Track1
	defw LonelyRoadHB_Subsong0_Track7
	defw LonelyRoadHB_Subsong0_Track3
	defw LonelyRoadHB_Subsong0_LinkerBlock1

; Position 3
LonelyRoadHB_Subsong0_Linker_Loop:
	defw LonelyRoadHB_Subsong0_Track4
	defw LonelyRoadHB_Subsong0_Track5
	defw LonelyRoadHB_Subsong0_Track6
	defw LonelyRoadHB_Subsong0_LinkerBlock1

; Position 4
	defw LonelyRoadHB_Subsong0_Track4
	defw LonelyRoadHB_Subsong0_Track7
	defw LonelyRoadHB_Subsong0_Track6
	defw LonelyRoadHB_Subsong0_LinkerBlock1

; Position 5
	defw LonelyRoadHB_Subsong0_Track8
	defw LonelyRoadHB_Subsong0_Track9
	defw LonelyRoadHB_Subsong0_Track10
	defw LonelyRoadHB_Subsong0_LinkerBlock2

; Position 6
	defw LonelyRoadHB_Subsong0_Track8
	defw LonelyRoadHB_Subsong0_Track11
	defw LonelyRoadHB_Subsong0_Track12
	defw LonelyRoadHB_Subsong0_LinkerBlock3

; Position 7
	defw LonelyRoadHB_Subsong0_Track4
	defw LonelyRoadHB_Subsong0_Track5
	defw LonelyRoadHB_Subsong0_Track6
	defw LonelyRoadHB_Subsong0_LinkerBlock1

; Position 8
	defw LonelyRoadHB_Subsong0_Track4
	defw LonelyRoadHB_Subsong0_Track7
	defw LonelyRoadHB_Subsong0_Track6
	defw LonelyRoadHB_Subsong0_LinkerBlock1

; Position 9
	defw LonelyRoadHB_Subsong0_Track8
	defw LonelyRoadHB_Subsong0_Track9
	defw LonelyRoadHB_Subsong0_Track10
	defw LonelyRoadHB_Subsong0_LinkerBlock2

; Position 10
	defw LonelyRoadHB_Subsong0_Track8
	defw LonelyRoadHB_Subsong0_Track13
	defw LonelyRoadHB_Subsong0_Track12
	defw LonelyRoadHB_Subsong0_LinkerBlock3

; Position 11
	defw LonelyRoadHB_Subsong0_Track1
	defw LonelyRoadHB_Subsong0_Track14
	defw LonelyRoadHB_Subsong0_Track15
	defw LonelyRoadHB_Subsong0_LinkerBlock1

; Position 12
	defw LonelyRoadHB_Subsong0_Track1
	defw LonelyRoadHB_Subsong0_Track16
	defw LonelyRoadHB_Subsong0_Track15
	defw LonelyRoadHB_Subsong0_LinkerBlock1

; Position 13
	defw LonelyRoadHB_Subsong0_Track17
	defw LonelyRoadHB_Subsong0_Track18
	defw LonelyRoadHB_Subsong0_Track19
	defw LonelyRoadHB_Subsong0_LinkerBlock1

; Position 14
	defw LonelyRoadHB_Subsong0_Track20
	defw LonelyRoadHB_Subsong0_Track21
	defw LonelyRoadHB_Subsong0_Track22
	defw LonelyRoadHB_Subsong0_LinkerBlock1

LonelyRoadHB_Subsong0_DisarkPointerRegionEnd1:
	defw 0	; Loop.
LonelyRoadHB_Subsong0_DisarkWordForceReference2:
	defw LonelyRoadHB_Subsong0_Linker_Loop

LonelyRoadHB_Subsong0_LinkerBlock0:
	defb 4	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
LonelyRoadHB_Subsong0_DisarkWordForceReference3:
	defw LonelyRoadHB_Subsong0_SpeedTrack0	; SpeedTrack address.
LonelyRoadHB_Subsong0_DisarkWordForceReference4:
	defw LonelyRoadHB_Subsong0_EventTrack0	; EventTrack address.
LonelyRoadHB_Subsong0_LinkerBlock1:
	defb 64	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
LonelyRoadHB_Subsong0_DisarkWordForceReference5:
	defw LonelyRoadHB_Subsong0_SpeedTrack0	; SpeedTrack address.
LonelyRoadHB_Subsong0_DisarkWordForceReference6:
	defw LonelyRoadHB_Subsong0_EventTrack0	; EventTrack address.
LonelyRoadHB_Subsong0_LinkerBlock2:
	defb 48	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
LonelyRoadHB_Subsong0_DisarkWordForceReference7:
	defw LonelyRoadHB_Subsong0_SpeedTrack0	; SpeedTrack address.
LonelyRoadHB_Subsong0_DisarkWordForceReference8:
	defw LonelyRoadHB_Subsong0_EventTrack0	; EventTrack address.
LonelyRoadHB_Subsong0_LinkerBlock3:
	defb 32	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
LonelyRoadHB_Subsong0_DisarkWordForceReference9:
	defw LonelyRoadHB_Subsong0_SpeedTrack0	; SpeedTrack address.
LonelyRoadHB_Subsong0_DisarkWordForceReference10:
	defw LonelyRoadHB_Subsong0_EventTrack0	; EventTrack address.

LonelyRoadHB_Subsong0_Track0:
	defb 60	; Waits for 1 line.

	defb 140
	defb 2	; New Instrument (2).
	defb 14
	defb 17
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track1:
	defb 152
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 24
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 24
	defb 60	; Waits for 1 line.

	defb 24
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 24
	defb 60	; Waits for 1 line.

	defb 24
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 24
	defb 60	; Waits for 1 line.

	defb 24
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 24
	defb 60	; Waits for 1 line.

	defb 24
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 24
	defb 60	; Waits for 1 line.

	defb 24
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 24
	defb 60	; Waits for 1 line.

	defb 24
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 24
	defb 60	; Waits for 1 line.

	defb 24
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track2:
	defb 147
	defb 2	; New Instrument (2).
	defb 19
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 147
	defb 2	; New Instrument (2).
	defb 19
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 22
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 17
	defb 60	; Waits for 1 line.

	defb 19
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 140
	defb 2	; New Instrument (2).
	defb 14
	defb 17
	defb 19
	defb 22
	defb 147
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 16
	defb 62 + 2 * 64	; Optimized wait for 4 lines.

	defb 140
	defb 2	; New Instrument (2).
	defb 14
	defb 17
	defb 19
	defb 19
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 147
	defb 2	; New Instrument (2).
	defb 19
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 22
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 17
	defb 60	; Waits for 1 line.

	defb 19
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 152
	defb 2	; New Instrument (2).
	defb 26
	defb 29
	defb 31
	defb 34
	defb 164
	defb 1	; New Instrument (1).
	defb 61, 5	; Waits for 6 lines.

	defb 140
	defb 2	; New Instrument (2).
	defb 14
	defb 17
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track3:
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track4:
	defb 152
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 152
	defb 5	; New Instrument (5).
	defb 24
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track5:
	defb 147
	defb 2	; New Instrument (2).
	defb 19
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 147
	defb 2	; New Instrument (2).
	defb 19
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 22
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 17
	defb 60	; Waits for 1 line.

	defb 19
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 140
	defb 2	; New Instrument (2).
	defb 14
	defb 17
	defb 19
	defb 22
	defb 147
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 16
	defb 62 + 2 * 64	; Optimized wait for 4 lines.

	defb 140
	defb 2	; New Instrument (2).
	defb 14
	defb 17
	defb 19
	defb 19
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 147
	defb 2	; New Instrument (2).
	defb 19
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 22
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 17
	defb 60	; Waits for 1 line.

	defb 19
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 152
	defb 2	; New Instrument (2).
	defb 26
	defb 29
	defb 31
	defb 34
	defb 164
	defb 1	; New Instrument (1).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 29
	defb 60	; Waits for 1 line.

	defb 156
	defb 2	; New Instrument (2).
	defb 12
	defb 14
	defb 17
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track6:
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 174
	defb 8	; New Instrument (8).
	defb 46
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 46
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 46
	defb 46
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 46
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 46
	defb 46
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 46
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 173
	defb 7	; New Instrument (7).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 45
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 174
	defb 8	; New Instrument (8).
	defb 46
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 46
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 46
	defb 46
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 46
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 46
	defb 46
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 46
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 48
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 48
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track7:
	defb 147
	defb 2	; New Instrument (2).
	defb 19
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 147
	defb 2	; New Instrument (2).
	defb 19
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 22
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 17
	defb 60	; Waits for 1 line.

	defb 19
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 140
	defb 2	; New Instrument (2).
	defb 14
	defb 17
	defb 19
	defb 22
	defb 147
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 16
	defb 62 + 2 * 64	; Optimized wait for 4 lines.

	defb 140
	defb 2	; New Instrument (2).
	defb 14
	defb 17
	defb 19
	defb 19
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 147
	defb 2	; New Instrument (2).
	defb 19
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 22
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 17
	defb 60	; Waits for 1 line.

	defb 19
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 152
	defb 2	; New Instrument (2).
	defb 26
	defb 29
	defb 31
	defb 34
	defb 164
	defb 1	; New Instrument (1).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 29
	defb 60	; Waits for 1 line.

	defb 28
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track8:
	defb 152
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 24
	defb 60	; Waits for 1 line.

	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 160
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 152
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 24
	defb 60	; Waits for 1 line.

	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 160
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 152
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 24
	defb 60	; Waits for 1 line.

	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 160
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 152
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 24
	defb 60	; Waits for 1 line.

	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 160
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 152
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 24
	defb 60	; Waits for 1 line.

	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 160
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 152
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 24
	defb 60	; Waits for 1 line.

	defb 152
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 160
	defb 5	; New Instrument (5).
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track9:
	defb 143
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 15
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 149
	defb 2	; New Instrument (2).
	defb 150
	defb 1	; New Instrument (1).
	defb 62 + 2 * 64	; Optimized wait for 4 lines.

	defb 26
	defb 60	; Waits for 1 line.

	defb 155
	defb 2	; New Instrument (2).
	defb 157
	defb 1	; New Instrument (1).
	defb 62 + 2 * 64	; Optimized wait for 4 lines.

	defb 27
	defb 60	; Waits for 1 line.

	defb 154
	defb 2	; New Instrument (2).
	defb 152
	defb 1	; New Instrument (1).
	defb 61, 7	; Waits for 8 lines.

	defb 15
	defb 60	; Waits for 1 line.

	defb 15
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 149
	defb 2	; New Instrument (2).
	defb 150
	defb 1	; New Instrument (1).
	defb 62 + 2 * 64	; Optimized wait for 4 lines.

	defb 26
	defb 60	; Waits for 1 line.

	defb 27
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track10:
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 231
	defb 6	; New Instrument (6).
	defb 0	; Index to an effect block.
	defb 39
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 39
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 110
	defb 1	; Index to an effect block.
	defb 46
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 46
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 105
	defb 0	; Index to an effect block.
	defb 41
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 41
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 112
	defb 1	; Index to an effect block.
	defb 48
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 48
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 103
	defb 0	; Index to an effect block.
	defb 39
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 39
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 110
	defb 1	; Index to an effect block.
	defb 46
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 46
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track11:
	defb 145
	defb 2	; New Instrument (2).
	defb 17
	defb 17
	defb 17
	defb 145
	defb 1	; New Instrument (1).
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 140
	defb 2	; New Instrument (2).
	defb 17
	defb 17
	defb 17
	defb 17
	defb 145
	defb 1	; New Instrument (1).
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 147
	defb 2	; New Instrument (2).
	defb 12
	defb 12
	defb 12
	defb 12
	defb 140
	defb 1	; New Instrument (1).
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 135
	defb 2	; New Instrument (2).
	defb 12
	defb 12
	defb 140
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 142
	defb 2	; New Instrument (2).
	defb 12
	defb 14
	defb 17
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track12:
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 233
	defb 6	; New Instrument (6).
	defb 0	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 41
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 41
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 41
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 112
	defb 1	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 48
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 48
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 48
	defb 124	; No note, but effects.
	defb 4	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track13:
	defb 145
	defb 2	; New Instrument (2).
	defb 17
	defb 17
	defb 17
	defb 145
	defb 1	; New Instrument (1).
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 140
	defb 2	; New Instrument (2).
	defb 17
	defb 17
	defb 17
	defb 17
	defb 145
	defb 1	; New Instrument (1).
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 147
	defb 2	; New Instrument (2).
	defb 12
	defb 12
	defb 12
	defb 12
	defb 140
	defb 1	; New Instrument (1).
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 135
	defb 2	; New Instrument (2).
	defb 12
	defb 12
	defb 140
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 142
	defb 2	; New Instrument (2).
	defb 12
	defb 142
	defb 1	; New Instrument (1).
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track14:
	defb 60	; Waits for 1 line.

	defb 145
	defb 2	; New Instrument (2).
	defb 19
	defb 17
	defb 19
	defb 150
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 26
	defb 62 + 2 * 64	; Optimized wait for 4 lines.

	defb 26
	defb 60	; Waits for 1 line.

	defb 153
	defb 2	; New Instrument (2).
	defb 152
	defb 1	; New Instrument (1).
	defb 61, 7	; Waits for 8 lines.

	defb 150
	defb 2	; New Instrument (2).
	defb 22
	defb 22
	defb 22
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 17
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 145
	defb 2	; New Instrument (2).
	defb 19
	defb 17
	defb 19
	defb 150
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 14
	defb 62 + 2 * 64	; Optimized wait for 4 lines.

	defb 26
	defb 60	; Waits for 1 line.

	defb 153
	defb 2	; New Instrument (2).
	defb 152
	defb 1	; New Instrument (1).
	defb 61, 7	; Waits for 8 lines.

	defb 145
	defb 2	; New Instrument (2).
	defb 17
	defb 17
	defb 17
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 18
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track15:
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 235
	defb 6	; New Instrument (6).
	defb 3	; Index to an effect block.
	defb 43
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 43
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 114
	defb 2	; Index to an effect block.
	defb 50
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 50
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 48
	defb 48
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 48
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 117
	defb 1	; Index to an effect block.
	defb 53
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 53
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 119
	defb 6	; Index to an effect block.
	defb 55
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 55
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 114
	defb 2	; Index to an effect block.
	defb 50
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 50
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 48
	defb 48
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 48
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 105
	defb 0	; Index to an effect block.
	defb 41
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 41
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track16:
	defb 60	; Waits for 1 line.

	defb 145
	defb 2	; New Instrument (2).
	defb 19
	defb 17
	defb 19
	defb 150
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 26
	defb 62 + 2 * 64	; Optimized wait for 4 lines.

	defb 26
	defb 60	; Waits for 1 line.

	defb 153
	defb 2	; New Instrument (2).
	defb 152
	defb 1	; New Instrument (1).
	defb 61, 7	; Waits for 8 lines.

	defb 150
	defb 2	; New Instrument (2).
	defb 22
	defb 22
	defb 22
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 17
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 145
	defb 2	; New Instrument (2).
	defb 19
	defb 17
	defb 19
	defb 150
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 14
	defb 62 + 2 * 64	; Optimized wait for 4 lines.

	defb 26
	defb 60	; Waits for 1 line.

	defb 153
	defb 2	; New Instrument (2).
	defb 152
	defb 1	; New Instrument (1).
	defb 61, 7	; Waits for 8 lines.

	defb 145
	defb 2	; New Instrument (2).
	defb 17
	defb 17
	defb 17
	defb 145
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 17
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track17:
	defb 152
	defb 3	; New Instrument (3).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 4	; New Instrument (4).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 152
	defb 4	; New Instrument (4).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 4	; New Instrument (4).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 152
	defb 4	; New Instrument (4).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 4	; New Instrument (4).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 152
	defb 4	; New Instrument (4).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 4	; New Instrument (4).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 152
	defb 4	; New Instrument (4).
	defb 148
	defb 5	; New Instrument (5).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 148
	defb 5	; New Instrument (5).
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track18:
	defb 150
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 154
	defb 2	; New Instrument (2).
	defb 27
	defb 26
	defb 22
	defb 17
	defb 147
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 145
	defb 2	; New Instrument (2).
	defb 147
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 147
	defb 2	; New Instrument (2).
	defb 17
	defb 147
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 20
	defb 60	; Waits for 1 line.

	defb 20
	defb 60	; Waits for 1 line.

	defb 148
	defb 2	; New Instrument (2).
	defb 19
	defb 17
	defb 143
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 143
	defb 2	; New Instrument (2).
	defb 19
	defb 19
	defb 20
	defb 20
	defb 21
	defb 21
	defb 150
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 154
	defb 2	; New Instrument (2).
	defb 27
	defb 26
	defb 22
	defb 17
	defb 147
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 145
	defb 2	; New Instrument (2).
	defb 147
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 147
	defb 2	; New Instrument (2).
	defb 17
	defb 147
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 20
	defb 60	; Waits for 1 line.

	defb 20
	defb 60	; Waits for 1 line.

	defb 148
	defb 2	; New Instrument (2).
	defb 19
	defb 17
	defb 143
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 143
	defb 2	; New Instrument (2).
	defb 14
	defb 14
	defb 15
	defb 15
	defb 16
	defb 16
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track19:
	defb 238
	defb 6	; New Instrument (6).
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 46
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 107
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 43
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 43
	defb 43
	defb 43
	defb 60	; Waits for 1 line.

	defb 108
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 44
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 103
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 39
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 39
	defb 39
	defb 39
	defb 60	; Waits for 1 line.

	defb 110
	defb 5	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 46
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 107
	defb 3	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 43
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 43
	defb 43
	defb 43
	defb 60	; Waits for 1 line.

	defb 108
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 44
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 115
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 51
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 51
	defb 51
	defb 51
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track20:
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 140
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 12
	defb 60	; Waits for 1 line.

	defb 12
	defb 60	; Waits for 1 line.

	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 24
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 152
	defb 4	; New Instrument (4).
	defb 152
	defb 3	; New Instrument (3).
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track21:
	defb 145
	defb 2	; New Instrument (2).
	defb 12
	defb 17
	defb 15
	defb 10
	defb 15
	defb 17
	defb 12
	defb 17
	defb 20
	defb 148
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 20
	defb 60	; Waits for 1 line.

	defb 20
	defb 60	; Waits for 1 line.

	defb 145
	defb 2	; New Instrument (2).
	defb 12
	defb 17
	defb 15
	defb 10
	defb 15
	defb 145
	defb 1	; New Instrument (1).
	defb 61, 8	; Waits for 9 lines.

	defb 145
	defb 2	; New Instrument (2).
	defb 12
	defb 17
	defb 15
	defb 10
	defb 15
	defb 17
	defb 12
	defb 17
	defb 20
	defb 148
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 20
	defb 60	; Waits for 1 line.

	defb 20
	defb 60	; Waits for 1 line.

	defb 150
	defb 2	; New Instrument (2).
	defb 17
	defb 22
	defb 20
	defb 15
	defb 20
	defb 17
	defb 12
	defb 17
	defb 15
	defb 143
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 15
	defb 60	; Waits for 1 line.

	defb 15
	defb 61, 127	; Waits for 128 lines.


LonelyRoadHB_Subsong0_Track22:
	defb 233
	defb 6	; New Instrument (6).
	defb 0	; Index to an effect block.
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 39
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 41
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 44
	defb 44
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 41
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 39
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 41
	defb 61, 8	; Waits for 9 lines.

	defb 41
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 39
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 41
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 44
	defb 44
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 46
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 44
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 41
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 39
	defb 39
	defb 60	; Waits for 1 line.

	defb 39
	defb 60	; Waits for 1 line.

	defb 39
	defb 124	; No note, but effects.
	defb 4	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


; The speed tracks
LonelyRoadHB_Subsong0_SpeedTrack0:
	defb 16	; Value: 8.
	defb 253	; Wait for 127 lines.

; The event tracks
LonelyRoadHB_Subsong0_EventTrack0:
	defb 255	; Wait for 128 lines.

LonelyRoadHB_Subsong0_DisarkByteRegionEnd0:
